### ISSUE TITLE
W3C TAG review

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-temporal#102]
The TAG is reviewing this proposal! See the thread at https://github.com/w3ctag/design-reviews/issues/311

**Comment by ryzokuken** [comment]
Since they have tagged the issue as “review: complete” and this was purely meant to notify concerned parties, closing this.

**Comment by littledan** [comment]
Once we've finalized this new version, let's ask the TAG for another review, given that we have made changes based on their feedback. This is the TAG's typical workflow.

**Comment by ptomato** [comment]
The second review has been requested: https://github.com/w3ctag/design-reviews/issues/311#issuecomment-734812490

**Comment by littledan** [comment]
We should respond to the latest TAG review in https://github.com/w3ctag/design-reviews/issues/311#issuecomment-768948852 . I think we have good reasons for the design decisions Temporal has made, and the main thing is to explain that in response to the TAG's suggestions.

**Comment by ptomato** [comment]
I've responded there.
