### ISSUE TITLE
Rollup issue about custom time zones

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#1037]
There are several open issues related to custom time zones. I think it might be easier to discuss all of these issues together because the answer to one might influence our decision on the others. LMK if I missed any. 

1. Must `ZonedDateTime.prototype.timeZone` be a TimeZone?  Or can it be a TimeZoneProtocol with some TimeZone properties and methods not implemented?  If the latter, how to address the usability concerns outlined in https://github.com/tc39/proposal-temporal/issues/810#issuecomment-711429469?

2) Does `TimeZone.from` always clone the input, or are there cases where it will return the same input back to the user? If "same input back" then is this an SES concern? #810

3) Can custom time zones be plain objects or must they inherit from TimeZone?  If "must inherit" then how do we handle cross-realm cases noted by @gibson042 (FYI - @littledan had questions about this in https://github.com/tc39/proposal-temporal/issues/925#issuecomment-713125950)

4) How do the answers above vary (if at all) for custom calendars vs. custom time zones?

**Comment by ptomato** [comment]
I think we can close this one in favour of #1040/#1041.
