### ISSUE TITLE
Calendar.prototype.fields feedback

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#1054]
I'm catching up on all the activity last week and I just reviewed #1014 which was just merged before I reviewed it, so opening a new issue. Sorry I didn't get to this yesterday!  A few things:

1. Do we allow calendars to remove fields?  Or only add them?  If the latter, then why not have the calendar only return a list of additional fields, with the advantage that the list of new fields could be a static object instead of having to clone and concatenate an array every time. 

2. I'm assuming that the `fields()` method should be deterministic, with the the same input fields always yielding the same output. Is this correct? If so, then should this method be a property, e.g. that returned a record like this?
```js
const eraField = Object.freeze(['era']);
const extraFields = Object.freeze({
  plainDate: eraField,
  plainYearMonth: eraField,
  // plainMonthDay: undefined, 
  // plainTime: undefined, 
  zonedDateTime:  eraField,
  plainDateTime: eraField
});
export class SomeCalendar extends Temporal.Calendar {
  constructor() { super('some'); }
  get extraFieldNames() { return extraFields; }
  //   . . .
}
```

Some possible advantages of a property:
* Nice debugger DX for non-ISO calendars so you can see all the expected extra fields for this calendar. Example: 
```js
date = Temporal.Date.from({ year: 2020, month: 1, day: 1, calendar: new SomeCalendar()});
s = date.calendar;
```
![image](https://user-images.githubusercontent.com/277214/97089164-dda46080-15ea-11eb-9718-58646d344545.png)
* Easier to implement calendars because no code required.
* Less chance of errors, e.g. custom calendar implementer forgetting that MonthDay shouldn't have `era`
* More obviously cacheable. Caching could also work with the current implementation if we document that its results should be deterministic, but the shape of the current API isn't a great match for a deterministic, static data.
* Better forwards compatibility if Temporal for some insane reason adds another type in the future. With the current API there's not really a way for a calendar to say "I don't know about this type" if the new type shares fields with other types. 
* I'm pretty sure (although not 100%) that it'd make a better TypeScript-friendly solution for custom fields because the property could be trivially exposed as a TS type.

3. Is naming it `fields()` confusable with `getFields()`?  Should it be called something like `fieldNames` instead?

**Comment by ptomato** [comment]
Meeting, Oct 29: Flexibility for removing fields and dealing with userland types is desired. None of the alternatives are enough of a clear improvement over the existing method to risk delaying the proposal, so we'll leave this as is.
