### ISSUE TITLE
Remove `calendar.prototype.xxxSubtract()` methods? (use xxxAdd instead)

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#1066]
From https://github.com/tc39/proposal-temporal/pull/1060#discussion_r512325613:

> > @justingrant We have both `dateAdd` and `dateSubtract` but only one `dateUntil` (not `dateSince`). Why do we have two methods in one place but only one method here? IMHO, one method in both places might be cleanest.

> @ptomato I believe we could consolidate `dateAdd()` and `dateSubtract()` once #993 is completed, but not before.

cc @ryzokuken

**Comment by ptomato** [comment]
I think this should be done as part of #993, closing in favour of that one.
