### ISSUE TITLE
test262 on github actions sometimes fails with ijson.common.IncompleteJSONError: parse error: premature EOF

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-temporal#1094]
e.g. https://github.com/tc39/proposal-temporal/pull/1090/checks?check_run_id=1342863111

**Comment by justingrant** [comment]
FWIW, these failures show up when running locally, not just in CI.

**Comment by Ms2ger** [comment]
That's surprising, I never hit them locally. You don't happen to feel like debugging?

**Comment by justingrant** [comment]
It's intermittent locally. Sometimes crashes, sometimes not.  Happy to try to debug but not sure where to dig.

Sent from my mobile device.
________________________________

**Comment by justingrant** [comment]
I took a look at this problem and found one obvious fix which was to remove test source code output which was causing GBs of piped I/O that the reporter script wasn't using. PR at #1187.  A nice side effect of removing this is that tests are now over 10x faster. 

Also, it's weird that we're using Python for reporting results. I'll take a look to see if it'd be easy to replace with a plain-JS reporter script.

**Comment by Ms2ger** [comment]
Thanks @justingrant! I made test262 required for merging again, but can turn it off again if it turns out it isn't stable enough yet
