### ISSUE TITLE
Temporal.Date.prototype.toLocaleString doesn't output era for Gregorian calendar

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#1100]
```js
date = Temporal.Date.from({ era: 'bc', year: 753, month: 4, day: 21, calendar: 'gregory' });
// => -000752-04-21[c=gregory]
date.toLocaleString({year: 'numeric', month: 'numeric', day: 'numeric', era: 'short'});
// => 4/21/753
date.toLocaleString();
// => 4/21/753
```

Expected?  Seems like there are two possible issues:
1) Era isn't printed when it should be
2) Seems like the default output for a BC date should include the era by default. Not doing this seems quite confusing!

**Comment by sffc** [comment]
This is a 402/ICU/CLDR bug.  I feel like I've seen it before.  It happens on legacy Date too:

```javascript
new Date(-753, 5, 21).toLocaleDateString()
// "6/21/754"
```

I'm closing this issue in favor of https://github.com/tc39/ecma402/issues/508.
