### ISSUE TITLE
Review calendar annotations in MonthDay/YearMonth toString

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-temporal#1104]
Followup from #1081. This seems to be the only place where we use _calendar_.[[Identifier]] rather than CalendarToString.

**Comment by ptomato** [comment]
This seems to have fixed itself in the meantime. The only places _calendar_.[[Identifier]] is now used, are in the calendar methods themselves, and the definitions in 402 that supersede them, to determine which calendar algorithm to use.
