### ISSUE TITLE
Should `until` and `since` throw if a `unit` option is provided without `largestUnit`?

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#1194]
Like `second` vs. `seconds`, another case where developers may confuse similar options is `unit` (in `total`) vs. `largestUnit` (in `until`, `since`, and `until`. For example, while writing a documentation sample, I created a bug when refactoring code from using `total` to `until`:

```
// original code
minutes = Math.trunc(duration.total({ unit: 'minutes', relativeTo }));

// refactored code
minutes = relativeTo.until(relativeTo.add(duration), { unit: 'minutes'});
// BUG!  `unit` is not recognized, but no error
```

Should `until` and `since` throw if presented with a `unit` option?  Or throw if `largestUnit` is not present?

Note that this is unlikely to be a problem in `total` because `unit` is required, and fairly unlikely in `round` because either `smallestUnit` or `largestUnit` is required. However, `until` and `since` are vulnerable because neither `largestUnit` nor `smallestUnit` are required.

**Comment by ptomato** [comment]
Presumably types would help avoid these bugs. I don't think it's the case in any other APIs taking options objects in Intl, that they check for similarly-named options and throw.

In any case, I think changing this now is incompatible with our goal of stopping further API changes except for addressing implementer feedback.
