### ISSUE TITLE
date.until and date.since : largestUnit option control

### ISSUE THREAD

**Issue by Louis-Aime** [tc39/proposal-temporal#1198]
Playing in Temporal, I obtained this: 
`Uncaught RangeError: largestUnit must be one of auto, years, months, weeks, days, year, month, day, not week`
`    GetOption ecmascript.mjs:3581`
`    ToLargestTemporalUnit ecmascript.mjs:593`
`    since plaindate.mjs:239`
`    <anonymous> debugger eval code:1`

OK, I should have put `weeks` instead of `week`. But with `month` or `year`, I suppose the option would have been changed to `months` or `years`. Why not with `week` ?

**Comment by Ms2ger** [comment]
#1001:

> Both singular and plural should be accepted (but not "week" because there is no property anywhere named that).
