### ISSUE TITLE
Temporal.PlainDate.compare sometimes doesn't give 0 for the same date

### ISSUE THREAD

**Issue by Louis-Aime** [tc39/proposal-temporal#1199]
Let's have `one` and `two` as the same date in two different calendars (possibly one custom and one built-in).
Then `Temporal.PlainDate.compare(one, two)` will not yield 0, but rather 1 or -1. 

You solve by adding a common calendar, e.g.
`Temporal.PlainDate.compare(one.withCalendar("iso8601"), two.withCalendar("iso8601"))`
which adds some more burden to what @justingrant already mentionned in #1086 .

The documentation specifies that `TemporalPlainDate.compare` returns 0 if the dates are the same, irrespective of the calendar.

**Comment by ptomato** [comment]
This should be fixed in the documentation. Comparing calendars in compare() is a requirement for sort order to be stable; see discussion in https://github.com/tc39/proposal-temporal/pull/588.
