### ISSUE TITLE
invalid calendar identifier chinese

### ISSUE THREAD

**Issue by zeldajay** [tc39/proposal-temporal#1210]
![image](https://user-images.githubusercontent.com/754006/99621393-c417fc80-2a62-11eb-86c2-09722a798860.png)

**Comment by justingrant** [comment]
Hi @zeldajay - Thanks for the bug report. At this time, that error is expected because most non-ISO calendars have not been added yet to the Temporal polyfill. The only non-ISO calendars that are present in current builds are `gregory` and `japanese`.

More calendars will come online as this proposal moves forward in the TS39 stages. 

@sffc

**Comment by ryzokuken** [comment]
Hey @zeldajay! I think we can treat this issue to generally follow the progress for the chinese calendar. Do you know any commonly-used javascript libraries that implement the Chinese calendar or any specifications? They would really help us implement this calendar.

**Comment by justingrant** [comment]
FYI, an initial polyfill version of the Chinese calendar is in #1245.

**Comment by justingrant** [comment]
Hi @zeldajay - the Chinese calendar is now available in Temporal's main branch. If you find problems with this calendar, feel free to report a new issue. Thanks!

![image](https://user-images.githubusercontent.com/277214/107319448-b8314a80-6a53-11eb-83a5-d31ee759c83b.png)

![image](https://user-images.githubusercontent.com/277214/107319548-e2830800-6a53-11eb-9a02-9461c0e8d12c.png)

**Comment by zeldajay** [comment]
The output date format is not standard. e.g.
output："2001年闰四月29", expectation："2001年闰四月廿九"
output："2021年三月9", expectation："2021年三月初九"

**Comment by cjtenny** [comment]
Hi @zeldajay , the output of `.toLocaleString` isn't standardized - it is up to the implementation. If you try on a different engine, you may see a different result.
