### ISSUE TITLE
"Time zone protocol" deadlink

### ISSUE THREAD

**Issue by Krinkle** [tc39/proposal-temporal#1212]
There is a mention of something called a "time zone protocol" in the [Instant docs](https://tc39.es/proposal-temporal/docs/instant.html#toZonedDateTimeISO) ([perm](https://github.com/tc39/proposal-temporal/blob/a5797888e143cc450684dbae25de2453218ce6f0/docs/instant.md#methods)), but there linked anchor in question is not found on the destination page. I also could not find any other section or mention of "protocol" on that page.

**Comment by ptomato** [comment]
Thanks for reporting it!
