### ISSUE TITLE
inLeapYear references non-existent spec?

### ISSUE THREAD

**Issue by SLaks** [tc39/proposal-temporal#1215]
https://tc39.es/proposal-temporal/#sec-temporal.calendar.prototype.inleapyear

 > An ECMAScript implementation that includes the ECMA-402 Internationalization API must implement the inLeapYear method as specified in the ECMA-402 specification.

But the word "leap" never appears in https://www.ecma-international.org/ecma-402/7.0/index.html

**Comment by ptomato** [comment]
Thanks for reporting it! This just hadn't been written yet at the time. We now have all these missing methods to be added to ECMA-402 in their own section of the spec text: https://tc39.es/proposal-temporal/#sup-temporal.calendar.prototype.inleapyear
Closing, as I believe it's been resolved.
