### ISSUE TITLE
Update polyfill to use const aliases for built-in objects' methods?

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#1222]
This issue is a follow-up from @Ms2ger's feedback (see https://github.com/tc39/proposal-temporal/pull/1206#discussion_r535584419) to use const alias methods instead of directly using JS built-in objects' static methods like `Math.abs()`.

I wasn't sure about other usages of built-ins in ecmascript.js, so opening this issue for tracking.

1. Legacy Date is used (constructor, static now(), and prototype methods) but I wasn't sure if this is intentional (for SES) or not. So I didn't make any changes to its usage.

2. There were built-in prototype methods used too, but I wasn't sure if those needed to be replaced too so didn't change any. Here's the prototype methods I found that were used: 
* Regex.prototype.exec
* String.prototype.slice
* String.prototype.match
* String.prototype.split
* Array.prototype.map
* Array.prototype.filter
* Array.prototype.includes
* Array.prototype.some
* Array.prototype.push
* Array.prototype.unshift
* Array.prototype.join
* Set (constructor)
* Set.prorotype.has
* Set.prototype.delete
* Map (constructor)
* Map.prototype.has
* Map.prototype.get
* Map.prototype.keys
* Map.prototype.values

3. Finally, there's lots of use of prototype methods on `big-integer`, but I assumed because as an imported library there's no need to change those calls. 

4. There are other usages of static methods used outside of ecmascript.js (e.g. `Math.*` used in duration.mjs) but changing those seemed out of scope to #1206 so I didn't change those in that PR.

**Comment by ljharb** [comment]
You can use my https://npmjs.com/call-bind like this:
```js
const callBound = require('call-bind/callBound');

const $exec = callBound('RegExp.prototype.exec');

// and later, safely do:
$exec(regex, string);
```

(this is what I do in all of my polyfills/shims)
