### ISSUE TITLE
error messages resulting because instant is not calendar aware

### ISSUE THREAD

**Issue by henryw374** [tc39/proposal-temporal#1233]
java.time has the same distinction between calendar-aware-or-not entities - and in my experience as a maintainer of libraries around that [1], beginners and even intermediates trip up on this again and again. 

My proposal would be to improve the error messages when this mistake is made. For example

```
Temporal.now.instant().add(Temporal.Duration.from({years: 1}))  
```

The error message is correct, but it would save many people a lot of time if the message pointed people to a link about calendar-awareness or somehow explained the problem sufficiently.

[1]  https://github.com/henryw374/cljc.java-time/issues/18

**Comment by justingrant** [comment]
New proposed error message from #1343: 

> Duration field years not supported by Temporal.Instant. Try Temporal.ZonedDateTime instead.
