### ISSUE TITLE
Document how custom calendars should expose new fields

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#1234]
A common calendar use case is to expose custom fields, e.g. a "year animal" for an extended Chinese calendar. It's likely that most custom-calendar authors will be domain experts in that calendar, but may not be domain experts in JavaScript.  For these developers, it would be helpful to document how to expose custom fields.  

Specifically, are we recommending that calendar authors should extend the prototypes of PlainDate, PlainYearMonth, etc. to add their custom fields as getters? If yes, then we would ideally document a short example of how to do this for non-experts.  If not, then how are we expecting calendar authors to only expose fields to users via `getFields` or is there another option?

**Comment by ptomato** [comment]
No custom calendars, so no need to document this anymore.
