### ISSUE TITLE
Spec withZone()'s options argument

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-temporal#125]
Nothing explains what it's for; the polyfill seems to do some kind of filtering.

**Comment by pipobscure** [comment]
This is relevant only for `CivilDateTime.prototype.with()`

The reason for it is that this conversion may result zero, one or two results.

The accpeted parameter is either an offset-string (which has to match for the result to be accepted) or `ZonedDateTime.EARLIER`/`ZonedDateTime.LATER` to choose the earlier or later option available if any. The default is `ZonedDateTime.EARLIER`.

If no options matching the input an exception is thrown. This can happen when either the offset-string does not match any option, or there are no valid options.

**Comment by pipobscure** [comment]
This has been updated
