### ISSUE TITLE
Review prose around Temporal.Duration.prototype.toLocaleString

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-temporal#1258]
CC @ptomato @littledan 

See <https://github.com/tc39/proposal-temporal/pull/1247#discussion_r553795388>. If we don't want Temporal to depend on DurationFormat, perhaps this should be replaced by a non-normative reference to the DurationFormat specification, and the prose moved there?

**Comment by littledan** [comment]
My suggestion is to leave the current spec text as is, and then make an editor's note which cross-references Intl.DurationFormat. If Temporal gets to Stage 4 before Intl.DurationFormat, we can fix it up to be more accurate.
