### ISSUE TITLE
Instant.prototype.with seems to be missing

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-temporal#126]

**Comment by pipobscure** [comment]
`Instant` has no units that are combinable. So the `with` method makes no sense.

There is however:

 * `Instant.fromEpochSeconds()`
 * `Instant.fromEpochMilliseconds()`
 * `Instant.fromEpochMicroseconds()`
 * `Instant.fromEpochNanoseconds()`

to create new `Instant` objects with a specific value.

**Comment by littledan** [comment]
@pipobscure Good explanation. Do you think it could be written somewhere that learners of the API would have access to?
