### ISSUE TITLE
Method for shifting from one zone to the other?

### ISSUE THREAD

**Issue by thojanssens** [tc39/proposal-temporal#1288]
With the latest API, how are we intended to shift the zone for a `ZonedDateTime` from one time zone to another?

**Comment by Ms2ger** [comment]
[`Temporal.ZonedDateTime.prototype.withTimeZone`](https://tc39.es/proposal-temporal/#sec-temporal.zoneddatetime.prototype.withtimezone), perhaps?

**Comment by thojanssens** [comment]
It's not listed in the index:
https://tc39.es/proposal-temporal/docs/zoneddatetime.html

I'll have a look though

**Comment by Ms2ger** [comment]
Thanks for pointing that out. I notice a bunch of examples that use `with({ timeZone })` as well; those also need fixing.
