### ISSUE TITLE
Version of tzdata

### ISSUE THREAD

**Issue by thojanssens** [tc39/proposal-temporal#1317]
Is there a function returning the version of the time zone database?

E.g. tzdata2020f

**Comment by ryzokuken** [comment]
No, and I'm not sure if that would make the implementation more vulnerable...

**Comment by thojanssens** [comment]
Other languages/libraries allow showing the version of the tzdata. Also, it is important to know for advanced users/cases.

As an example, for some reason I need to store the utc datetime of a datetime with time zone, but I store the tzdata version as well. Whenever the tzdata version changes, I recompute that stored utc datetime.

Other things in mind, my server language uses its own library with a specific tzdata version, and JS Temporal has its own tzdata version; it might be useful to check if both versions are the same, and if not emit a warning log.

More generally, if you store a datetime and a time zone, you still don't have a unique datetime; you need to add the tzdata version.

**Comment by jasonwilliams** [comment]
> Other languages/libraries allow showing the version of the tzdata

Hey @thojanssens do you have some examples where this is being exposed and used? What frameworks, languages etc

**Comment by thojanssens** [comment]
PHP
https://www.php.net/manual/en/function.timezone-version-get.php

Python
`tzdata.IANA_VERSION`
https://tzdata.readthedocs.io/en/latest/

In Elixir I use a library and that provides a function to dump the version.

**Comment by justingrant** [comment]
> I'm not sure but that might make the implementation more vulnerable...

@ryzokuken If you want to test for a specific tzdata version, it's easy to do that: just convert the local time in some time zone to UTC and compare it to a known UTC value. If the "old" tz rules are in place, you'll get one value, and if the "new" rules are active then you'll get another value. An attacker (or a polyfill) could build a tz version detector using this approach. What additional safety is provided by not offering tzdata version?

One thing to note: we'd probably want to put the version on the TimeZone prototype, not the TimeZone constructor. This would accommodate the currently-speced behavior where the only guarantee is that the version is the same for each time zone for the life of the process, but it's only recommended but not guaranteed that all zones share the same version. From the spec: 

> Time zone information is subject to change, and host environments may update their time zone information at any time. At a minimum, implementations must ensure that the time zone information for each particular value of timeZone individually remains constant starting from the time it is first accessed, for the lifetime of the surrounding agent. Furthermore, it is recommended that the time zone information for all values of timeZone as a whole remains the same for the lifetime of the surrounding agent.

BTW, this feature could be added in a V2 and is IMHO not a blocker for V1 so I'm going to tag it with the V2 label.

**Comment by ptomato** [comment]
This is not included in the revision of Temporal currently under review, but I've added it for discussion to Temporal V2 at https://github.com/js-temporal/proposal-temporal-v2/issues/12.
