### ISSUE TITLE
Suggestion: make calendar ID optional in `withCalendar()`

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#1324]
Suggestion for Temporal V2: `withCalendar` methods should allow `undefined` to mean the ISO 8601 calendar.

Context: the ISO calendar acts like a default or null calendar throughout Temporal.  For example, if the `calendar` property is missing in the input to `from`, then ISO is assumed. But if you have a maybe-non-ISO date and want to convert it to ISO (which will be a very common operation when accepting external data), the developer needs to spell out `'iso8601'` in every call site. This seems unnecessary. Can we make the parameter optional, and use ISO if it's omitted?

This is backwards compatible so it could be done in a post-V1 Temporal proposal.

**Comment by ptomato** [comment]
I've added this for discussion in Temporal V2: https://github.com/js-temporal/proposal-temporal-v2/issues/13
