### ISSUE TITLE
FormatCalendarAnnotation editor's note: resolved?

### ISSUE THREAD

**Issue by ljharb** [tc39/proposal-temporal#1412]
For stage 3, I think the exact form of https://tc39.es/proposal-temporal/#sec-temporal-formatcalendarannotation must be known. Is this resolved upstream?

**Comment by ptomato** [comment]
The exact form that is to be presented to the IETF DISPATCH WG on Monday 03-08 is known (and #1409 is open to sync the Temporal proposal to that form.) I don't think it's guaranteed that the IETF won't make further changes after it's adopted, but we've considered that having the annotation on a standards track is a reasonable requirement for Stage 3 (see https://github.com/tc39/proposal-temporal/blob/main/meetings/agenda-minutes-2021-01-07.md#ietf-draft-status; there are earlier discussions about this as well but I can't dig them up right at the moment.)
