### ISSUE TITLE
editor review: missing abstract operations

### ISSUE THREAD

**Issue by ljharb** [tc39/proposal-temporal#1416]
referenced in https://tc39.es/proposal-temporal/#sec-temporal-builtintimezonegetplaindatetimefor:
 - `GetPartsFromEpoch` has no definition (possibly meant to be https://tc39.es/proposal-temporal/#sec-temporal-getisopartsfromepoch ?)
 - `BalanceDateTime` has no definition (possibly meant to be https://tc39.es/proposal-temporal/#sec-temporal-balanceisodatetime ?)

referenced in https://tc39.es/proposal-temporal/#sec-temporal-builtintimezonegetinstantfor:
 - `GetEpochFromParts` has no definition (possibly meant to be https://tc39.es/proposal-temporal/#sec-temporal-getisopartsfromepoch ?)

**Comment by ptomato** [comment]
Thanks! I think this probably came from a rebase error. I sure wish ecmarkup would catch these things :smile:
