### ISSUE TITLE
Docs vs. spec/polyfill mismatch for type of `calendar` and `timeZone` params of constructors

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#1436]
The docs say that the `calendar` and `timeZone` arguments to Temporal constructors must be an object.  Example:

> - `timeZone` (`Temporal.TimeZone` or plain object): The time zone in which the event takes place.
> - `calendar` (optional `Temporal.Calendar` or plain object): Calendar used to interpret dates and times. Usually set to `'iso8601'`.

But the spec and the polyfill can also accept a string. Repro: 

```js
new Temporal.PlainDate(2000, 1, 1, 'chinese');
// => 2000-01-01[u-ca-chinese]
```

I assume the spec and polyfill are correct and the docs are wrong.  True?

**Comment by ptomato** [comment]
Yes, this should be updated in the documentation.

**Comment by ptomato** [comment]
This has been fixed in the meantime.
