### ISSUE TITLE
Outdated `zonedDateTime()` docs / polyfill?

### ISSUE THREAD

**Issue by artalar** [tc39/proposal-temporal#1437]
Example from [here](https://tc39.es/proposal-temporal/docs/zoneddatetime.html#daysInMonth) throw an error

!["Uncaught RangeError: Invalid calendar: undefined"](https://user-images.githubusercontent.com/27290320/110635294-fa1cf000-81bb-11eb-8694-b6e4c9562969.png)

By the way, I need to get the Moscow time and do it so:
```js
const moscowTime = Temporal.now
  .zonedDateTime(
    new Intl.DateTimeFormat().resolvedOptions().calendar,
    Temporal.TimeZone.from('Europe/Moscow'),
  )
```

Is there a better way to do it, without `new Intl.DateTimeFormat().resolvedOptions().calendar`?

**Comment by gilmoreorless** [comment]
You're right, those examples are incorrect. It looks like that docs page got missed in the updates around the `.now` methods (https://github.com/tc39/proposal-temporal/issues/292#issuecomment-695043343).

You can use `Temporal.now.zonedDateTimeISO()` to use the default ISO 8601 calendar without having to provide a calendar argument. Additionally, you can provide a string as the `timeZone` argument, without having to construct a `Temporal.TimeZone` object directly. For example:

```js
const moscowTime = Temporal.now.zonedDateTimeISO('Europe/Moscow')
```
