### ISSUE TITLE
Review node version in CI

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-temporal#1519]
In  #1518, node 14 failed while 12 and 15 passed.

Also, 15 apparently is reaching EOL.

**Comment by ptomato** [comment]
cc @justingrant 

We discussed this at the last Temporal meeting and Justin thought that probably a fix was shipped in 14.x that obsoleted the workarounds that we put in for incorrect calendar data. We agreed to fix the node 14.x tests ASAP to leave it in good shape. We also discussed elsewhere (I think on Matrix? but I can't find it right now) going forward to leave support for multiple node versions to the production polyfills.

I think it would make sense to support only node 16.x going forward.

**Comment by ptomato** [comment]
This was completed in #1528.
