### ISSUE TITLE
Seek plenary consensus for normative changes

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-temporal#1542]
* #1604
* https://github.com/tc39/proposal-temporal/pull/1541
* https://github.com/tc39/proposal-temporal/issues/1544
* #1592
* #1598 / #1601

**Comment by ptomato** [comment]
I converted this into a milestone: https://github.com/tc39/proposal-temporal/milestone/10

I'd be OK to close this issue but I left it for now in case you find it particularly useful for it to be pinned (which can't be done with a milestone)
