### ISSUE TITLE
Drop support for sub-minute offset format

### ISSUE THREAD

**Issue by ryzokuken** [tc39/proposal-temporal#1544]
Both ISO 8601-1 (not -2) and RFC 3339 only support offset precision until an integral number of minutes, and sub-minute precision is not covered. This was a Temporal-specific requirement that might take a longer time than expected in the standards track due to its controversial nature.

Therefore, it was decided by the champions that we will remove all serialization and deserialization of any string that includes such an offset. Temporal would allow nanosecond precision for offsets internally but it'll only be exposed in the serialization format at a later stage.

**Comment by ptomato** [comment]
Consensus on how we will address the IETF feedback:
 - Change `ZonedDateTime.toString()` and `Instant.toString()` to output time zone offsets only with minutes precision.
 - Change `ZonedDateTime.from()` to accept `HH:MM` precision for non-minute-offset time zones, even with `offset: 'reject'`.
 - No change to `ZonedDateTime.offset` property, `offset` property in property bags, and `TimeZone.getOffsetStringFor()`.
