### ISSUE TITLE
Documentation: what is wall-clock time?

### ISSUE THREAD

**Issue by rauschma** [tc39/proposal-temporal#1553]
That isn’t completely clear to me from the documentation.

**Comment by ljharb** [comment]
The time as it would appear on a clock on the wall - no timezone information.

**Comment by rauschma** [comment]
Interesting, I’ve never heard that term before. Thanks!

**Comment by ljharb** [comment]
I’ve usually heard the term “local time” for that, but for reasons i can’t recall some weren’t in favor of that term.

**Comment by rauschma** [comment]
True. With “local time”, I wouldn’t be entirely sure if there is time zone information or not (it could mean time based on the local time zone). But it’s zone-less time.

**Comment by ljharb** [comment]
Wall clock time is based on the local timezone too :-) you just don’t know what timezone it is without extra information (like “where here is”)

**Comment by ptomato** [comment]
It's defined at the top of https://tc39.es/proposal-temporal/docs/ambiguity.html, do you have a suggestion for where would be a better place to (additionally?) write about it?

**Comment by rauschma** [comment]
@ljharb What I meant: In the context of `Date` “local time” means that everything is seen through the lens of the system time zone. Wall clock time does no such thing.

**Comment by rauschma** [comment]
@ptomato The rough general principle I try to follow is to define terms before using them. I started reading page (*) and encountered “wall-clock time” without a prior definition.

Could page (*) start with a glossary? Or link to a glossary at the beginning?

(*) https://tc39.es/proposal-temporal/docs/index.html

**Comment by rauschma** [comment]
@ptomato OK, after rereading the sentence, I recognize that this is mostly my mistake:

> Read more about handling time zones, DST, and ambiguity in Temporal.

Given the preceding paragraph and that sentence, I assumed that the linked document was _only_ about ambiguity. But that’s not what the sentence says.

The only nit I can find is that the section “Understanding Clock Time vs. Exact Time” is relevant even for people who are not interested in “time zones, DST, and ambiguity”.

**Comment by rauschma** [comment]
@justingrant Cool! I’ve added a comment.
