### ISSUE TITLE
ToTemporalZonedDateTime: assertion failure with `{ offset: undefined }`

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-temporal#1555]
1. If Type(item) is Object, then
    1. Let offsetString be ? Get(fields, "offset").
    1. If offsetString is not undefined, set it to ? ToString(offsetString).
1. Let offsetNanoseconds be ? ParseTimeZoneOffsetString(offsetString). 

where ParseTimeZoneOffsetString starts

1. Assert: Type(offsetString) is String.

**Comment by ptomato** [comment]
This is fixed, I believe. If _offsetString_ is undefined, we set _offsetBehaviour_ to "wall", and we no longer go into ParseTimeZoneOffsetString.
