### ISSUE TITLE
Need to add era/eraYear to section 12.4 / 3.3 / 5.3 / 6.3 / 9.3

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/proposal-temporal#1556]
In Section 12.4 of the proposal
12.4 Properties of the Temporal.Calendar Prototype Object
https://tc39.es/proposal-temporal/#sec-properties-of-the-temporal-calendar-prototype-object

There are NO
Temporal.Calendar.prototype.era ( temporalDateLike ) 
Temporal.Calendar.prototype.eraYear ( temporalDateLike )

However, in section  
15.6.2 Properties of the Temporal.Calendar Prototype Object
there are era and earYear define. This make the number of property on these two prototype object inconsistent.

Please add them to 12.4 with a reasonable return, for example, return undefined

15.6.2.6 Temporal.Calendar.prototype.era ( temporalDateLike )
https://tc39.es/proposal-temporal/#sec-temporal.calendar.prototype.era
15.6.2.7 Temporal.Calendar.prototype.eraYear ( temporalDateLike )
https://tc39.es/proposal-temporal/#sec-temporal.calendar.prototype.erayear

Same as the following
15.6.5.2 get Temporal.PlainDate.prototype.era
https://tc39.es/proposal-temporal/#sec-get-temporal.plaindate.prototype.era
15.6.5.3 get Temporal.PlainDate.prototype.eraYear
https://tc39.es/proposal-temporal/#sec-get-temporal.plaindate.prototype.erayear
15.6.6.2 get Temporal.PlainDateTime.prototype.era
https://tc39.es/proposal-temporal/#sec-get-temporal.plaindatetime.prototype.era
15.6.6.3 get Temporal.PlainDateTime.prototype.eraYear
https://tc39.es/proposal-temporal/#sec-get-temporal.plaindatetime.prototype.erayear
15.6.9.2 get Temporal.PlainYearMonth.prototype.era
https://tc39.es/proposal-temporal/#sec-get-temporal.plainyearmonth.prototype.era
15.6.9.3 get Temporal.PlainYearMonth.prototype.eraYear
https://tc39.es/proposal-temporal/#sec-get-temporal.plainyearmonth.prototype.erayear
15.6.10.2 get Temporal.ZonedDateTime.prototype.era
https://tc39.es/proposal-temporal/#sec-get-temporal.zoneddatetime.prototype.era
15.6.10.3 get Temporal.ZonedDateTime.prototype.eraYear
https://tc39.es/proposal-temporal/#sec-get-temporal.zoneddatetime.prototype.erayear

These function should be added to section 3.3 / 5.3 / 6.3 / 9.3

@sffc @justingrant @ptomato @ryzokuken

**Comment by Ms2ger** [comment]
era and eraYear should only be defined in §15 per #1046.
