### ISSUE TITLE
Do we need to define %Temporal.PlainDateTime% (and other) somewhere?

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/proposal-temporal#1563]
Sorry to be noisy, I have hard time to understand how does these %Temporal.*% value work
I can only find the following places in the proposal mentioned "%Temporal.PlainDateTime%"

5.1 The Temporal.PlainDateTime Constructor
The Temporal.PlainDateTime constructor creates and initializes a new Temporal.PlainDateTime object when called as a constructor.

The Temporal.PlainDateTime constructor is designed to be subclassable. It may be used as the value of an extends clause of a class definition. Subclass constructors that intend to inherit the specified DateTime behaviour must include a super call to the %Temporal.PlainDateTime% constructor to create and initialize subclass instances with the necessary internal slots.
https://tc39.es/proposal-temporal/#sec-temporal-plaindatetime-constructor

5.3.1 Temporal.PlainDateTime.prototype.constructor
The initial value of Temporal.PlainDateTime.prototype.constructor is %Temporal.PlainDateTime%.
https://tc39.es/proposal-temporal/#sec-temporal.plaindatetime.prototype.constructor

5.5.6 CreateTemporalDateTime ( isoYear, isoMonth, isoDay, hour, minute, second, millisecond, microsecond, nanosecond, calendar [ , newTarget ] )
...
6. 6. If newTarget is not given, set it to %Temporal.PlainDateTime%.
https://tc39.es/proposal-temporal/#sec-temporal-createtemporaldatetime

But nowhere in the spec text define what is %Temporal.PlainDateTime%

Should we add some text to the constructor section with words like 
"The Temporal.PlainDateTime constructor  is the %Temporal.PlainDateTime% intrinsic object."

The reason I think this is necessary is because of the following spec text:

"
6. If newTarget is not given, set it to %Temporal.PlainDateTime%.
"

I have no idea what the newTarget should set to from the spec text today.

ref

23.1.1 The Array Constructor
The Array constructor:

is %Array%.
https://tc39.es/ecma262/#sec-array-constructor

23.2.1 The %TypedArray% Intrinsic Object
https://tc39.es/ecma262/#sec-%typedarray%-intrinsic-object

24.1.1 The Map Constructor
The Map constructor:

is %Map%.
https://tc39.es/ecma262/#sec-map-constructor

24.2.1 The Set Constructor
The Set constructor:

is %Set%.
https://tc39.es/ecma262/#sec-set-constructor

24.3.1 The WeakMap Constructor
The WeakMap constructor:

is %WeakMap%.
https://tc39.es/ecma262/#sec-weakmap-constructor

24.4.1 The WeakSet Constructor
The WeakSet constructor:

is %WeakSet%.
https://tc39.es/ecma262/#sec-weakset-constructor

25.1.3 The ArrayBuffer Constructor
The ArrayBuffer constructor:

is %ArrayBuffer%.
https://tc39.es/ecma262/#sec-arraybuffer-constructor

25.2.2 The SharedArrayBuffer Constructor
The SharedArrayBuffer constructor:

is %SharedArrayBuffer%.
https://tc39.es/ecma262/#sec-sharedarraybuffer-constructor

25.3.2 The DataView Constructor
The DataView constructor:

is %DataView%.
https://tc39.es/ecma262/#sec-dataview-constructor

there are many more in ecma262

**Comment by ptomato** [comment]
This was done intentionally in #1410 — I originally didn't know this, so previously it was done as you suggested, but the definition of %Temporal.PlainDateTime% is the initial value of the `PlainDateTime` property of %Temporal%.
