### ISSUE TITLE
Temporal Polyfill: Also polyfill `Date.prototype.toTemporalInstant()`?

### ISSUE THREAD

**Issue by rauschma** [tc39/proposal-temporal#1578]
Should the polyfill add method `.toTemporalInstant()` to `Date.prototype` if it doesn’t exist?

**Comment by Ms2ger** [comment]
There's code to do that in `polyfill/lib/init.js` and `polyfill/lib/shim.mjs`, so we must have found it useful in some cases. In any case, we should add or not add it unconditionally, to avoid breaking polyfill users if there's changes to the method by the time js engines ship it.

**Comment by rauschma** [comment]
My bad – I overlooked the difference between polyfilling vs. library (which doesn’t install anything globally):

* I used the latter and was wondering why `Date.prototype.toTemporalInstant()` didn’t work (but it shouldn’t – in this mode).
* Only the latter is documented in the readme. (But it looks like that was a deliberate decision.)

**Comment by rauschma** [comment]
FWIW – this way of installing the shim doesn’t work for me:

```js
import 'proposal-temporal/lib/shim.mjs';
```

Error:

```
Error [ERR_MODULE_NOT_FOUND]:
Cannot find module '/tmp/proj/node_modules/es-abstract/2020/Call.js.js'
imported from /tmp/proj/node_modules/proposal-temporal/lib/ecmascript.mjs
```

**Comment by ptomato** [comment]
At this point, I'd recommend using one of the [production polyfills](https://github.com/tc39/proposal-temporal#polyfills) instead.
