### ISSUE TITLE
ZonedDateTime constructor overloads?

### ISSUE THREAD

**Issue by apaprocki** [tc39/proposal-temporal#16]
I'm wondering -- Is there more explanation about the desired purpose of the additional overloads for the first parameter of the `ZonedDateTime` constructor?

- The constructor overloads that take `-HH:MM` / `HH:MM` or number of minutes West of GMT -- how does this differ from the proposed `OffsetDateTime`?

- What is the proposed behavior of the `undefined` or `SYSTEM` values? AFAIK there is no standards-defined way to determine the system IANA timezone string because it is not required that one be defined. If there is no way to get an IANA string from the system, then this would result in nothing more than an `OffsetDateTime` using the reported system offset. And `undefined`?

- Overloading the first parameter will slow down the 99% case, which I assume would be the IANA string. Would this also affect optimization possibilities in current optimizing compilers?

- Is it a `throw`-ing error if the IANA string is not available on the system (e.g. "sifhisfhs")?

Personally I would prefer to see this *only* take an IANA string and move `OffsetDateTime` from the future set into the initial set, since it is a much simpler type. Basically, implementing the two proposed overloads implements that type anyway. We currently universally use the exact proposed `OffsetDateTime` type alongside the built-in `Date` and it works very well. We provide IANA functionality via a static conversion function rather than a separate type, but either is acceptable.

**Comment by maggiepint** [comment]
Lots of stuff here, but with regard to the `SYSTEM` overload - it would take the system time zone, whether windows or IANA. This is how the current Date object works.

**Comment by apaprocki** [comment]
There is no guaranteed way to determine an IANA timezone on UNIX. It is not required to set one -- the system can be configured with a custom POSIX.1 timezone string (see https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html) such as "WGT3WGST,M3.5.0/-2,M10.5.0/-1". Other systems do not use IANA data at all (such as AIX). The current `Date` object uses the reported system offset from UTC, but it has no awareness of what the timezone is.

**Comment by maggiepint** [comment]
So is what you think this is saying that we need to get a time zone ID back? I understand that there are several time zone implementations, Windows, IANA, and many others. This does not attempt to determine the identifier - it just allows the system to use it's best judgement to determine time zone behavior.

**Comment by apaprocki** [comment]
Isn't the `ZonedDateTime` going to offer the IANA timezone as a property? Even if it didn't, wouldn't it certainly output the timezone in some form of `toString` interchange, otherwise how would you serialize it for databases and other systems?

In my mind the "system" can only ever output `OffsetDateTime` values because the system can only give the offset for a particular point in time. This is what built-in `Date` does. (This is what our C++ types offer. You can either request "now" in plain `DateTime` or `OffsetDateTime` using the system's offset.)

The `ZonedDateTime` would allow you to compute accurate UTC points in time for future datetimes in a given timezone. You can't do that with "system", especially if you want to serialize it and restore it back. I'd like to see the `ZonedDateTime` only contain an IANA timezone and be suitable for accurately representing future datetimes *and* be serializable across languages/platforms/machines. The IANA strings are the abstraction that allows that to be possible.

A concrete example would be the next TC39 meeting scheduled for 23 May 2017 10am `America/New_York`. A `ZonedDateTime` would represent that, and it could get serialized out to a database. If the US suddenly abolished DST tomorrow, reading that in from a database in any language/platform (with IANA support) would allow you to compute the accurate point in UTC because you have the timezone. If the type allowed you to specify "system", you'd lose the ability to send it across the wire and the other side would have the incorrect point in UTC after DST was abolished because all it has to go on is the offset at the point in time when it was serialized.

To me, "system" muddles what is a clean type and will lead to programmer error. If someone really wants the system to do whatever it feels like, then just represent future datetimes as just plain `DateTime` and every time you go to display them, let the system resolve them to exact `OffsetDateTime`s valid as of time-of-resolution using the system's opaque rules/data. (Behavior of the existing built-in `Date`)

**Comment by maggiepint** [comment]
So I need to break this down a bit. 

> In my mind the "system" can only ever output OffsetDateTime values because the system can only give the offset for a particular point in time. This is what built-in Date does. 

If you mean that the current date can only give you the offset for your current time as an output, you are correct. However, it can certainly follow system time zone rules to adjust for DST transitions. See this code:
```js
var a = new Date(); 
console.log(a.toISOString()); // 2017-05-13T17:24:40.053Z
a.setMonth(a.getMonth()+8);  
console.log(a.toISOString()) // 2018-01-13T18:24:40.053Z
```
As you can see, the hours place changes because I made a local time computation and the point on the global timeline adjusted for DST.

Are you suggesting that I take this away from users? Or are you suggesting that I compel implementations to use IANA time zones? Or something else?

**Comment by mj1856** [comment]
We have revised the proposal significantly.  `ZonedDateTime` has been replaced with `ZonedInstant`.  There is still a `timeZone` parameter during construction, which will indeed take multiple kinds of inputs, including `'SYSTEM'`.  Yes, there is also a `.timeZone` property, but it will only give back what is passed in.  This will accommodate systems where there is no IANA database, or where the local time zone has been customized.

The question then is, should there still be a method to try to retrieve the IANA time zone ID from the system if one is available?  What would the API for that be, perhaps `temporal.getSystemTimeZone()` as a top-level function?

**Comment by apaprocki** [comment]
Would the API throw if it couldn't be returned? Windows doesn't use IANA timezone names, so would it always throw in IE, or would they be required to use some kind of mapping (like the one in the CLDR)? @bterelson mentioned Windows deciding to ship ICU recently, but I'm guessing that is mostly for the text processing code and doesn't extend to its timezone support.

**Comment by mj1856** [comment]
Windows can already reverse map to IANA time zone names, without ICU.  Edge supports the ECMA-402 way to determine this:

```js
Intl.DateTimeFormat().resolvedOptions().timeZone
```

In fact, now that I think about it - we shouldn't even bother doing this, since it's in ECMA-402 already.  If we do anything at all, it would just be a convenience function pointing at that.

**Comment by apaprocki** [comment]
Ah, that apparently changed in the 2017 version of the spec. So is the value of that property always guaranteed to match whatever would be produced by passing in `SYSTEM`? If so, is `SYSTEM` necessary?

**Comment by mj1856** [comment]
It's necessary, because if the system has a custom time zone implementation, or just a custom time zone as allowed by both Windows and POSIX, then the ECMA-402 result would be `undefined`, even though there's still local time zone functionality.

Calling out the `SYSTEM` time zone allows implementers to hook into the native localtime conversion functions that would honor any customization.

Just because one can't give a time zone a known name doesn't mean there's not one present.

**Comment by apaprocki** [comment]
The current ECMA-402 spec language doesn't seem to allow custom Windows/POSIX time zones :( The spec doesn't say what happens if the host's time zone can't be represented as an IANA string:

> In this version of the ECMAScript 2017 Internationalization API, the timeZone property will be the name of the default time zone if no timeZone property was provided in the options object provided to the Intl.DateTimeFormat constructor. The first edition left the timeZone property *undefined* in this case.

and [6.4.3](https://tc39.github.io/ecma402/#sec-defaulttimezone):

> The DefaultTimeZone abstract operation returns a String value representing the valid (6.4.1) and canonicalized (6.4.2) time zone name for the host environment’s current time zone.

[6.4.1](https://tc39.github.io/ecma402/#sec-isvalidtimezonename):
> The IsValidTimeZoneName abstract operation verifies that the timeZone argument (which must be a String value) represents a valid Zone or Link name of the IANA Time Zone Database.

Some work might be needed there...

**Comment by maggiepint** [comment]
Direct support for non-IANA time zones will not get support from the committee, and is out of scope for this proposal. Windows time zones already map to IANA.

**Comment by maggiepint** [comment]
I"m going to close this because I think there is general consensus that, however inconvenient, it's going to be the way it is.
