### ISSUE TITLE
Casting Cross-Realm vs Same-Realm objects

### ISSUE THREAD

**Issue by pipobscure** [tc39/proposal-temporal#165]
Am I wrong in wanting:

a) cross-realm to cast to a current-realm object
b) current-realm to be a no-op

???

**Comment by ljharb** [comment]
I’d say yes; objects don’t tend to change which realm they are (ie, their [[Prototype]] doesn’t implicitly change to a similar object in the current realm).

“Cross-realm objects” remain so until they are Object.setPrototypeOf explicitly to the current realm’s relevant prototype object.

**Comment by pipobscure** [comment]
Ok, that means that in either case it should be a no-op (PR for this to follow)

**Comment by ljharb** [comment]
Thinking more about it, what do the existing builtins do? I don’t think constructors often take instances of themselves; Array.from always makes a new array, Promise.resolve directly returns anything with the internal slot, new RegExp given a regexp creates a new one from its slots, etc.

**Comment by pipobscure** [comment]
I guess `Promise` is the best analogy, because the state is similarly immutable. Regex & Array could be modified while the Promise resulting from `Promise.resolve` can't be externally altered in a semantically meaningful way by the user.

So I've opted for the *if it has the slot just return it approach*
