### ISSUE TITLE
Editorial request add Calendar prefix to 12.1.24|25|26 *FromFields

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/proposal-temporal#1670]
This is just an Editorial request to make our spec easier to follow
Currently we have many AOs named CalendarXXXX which all have pattern like

```
1. Let fields be ? GetMethod(calendar, "methodnames").
...
a. Set fieldsArray to ? Call(fields, calendar, « fieldsArray »).
```
in 12.1.5 - 12.1.8
or pattern like
```
2. Return ? Invoke(calendar, "methodnames", « dateLike »).
```
in 12.1.9 - 12.1.20

But three of the following also use Invoke but without the Calendar prefix
https://tc39.es/proposal-temporal/#sec-temporal-datefromfields
12.1.24 DateFromFields ( calendar, fields, options )
12.1.25 YearMonthFromFields ( calendar, fields [ , options ] )
12.1.26 MonthDayFromFields ( calendar, fields [ , options ] )

Could we rename it to follow the same naming patter as
12.1.24 CalendarDateFromFields ( calendar, fields, options )
12.1.25 CalendarYearMonthFromFields ( calendar, fields [ , options ] )
12.1.26 CalendarMonthDayFromFields ( calendar, fields [ , options ] )

to make it easier to understand.

Not very important but I think it may make the spec easier to follow.

**Comment by ptomato** [comment]
I may as well get this out of the way before refactoring the Calendar spec in #1808...
