### ISSUE TITLE
Be consistent in whether calendar operations using default options are called with undefined or Object.create(null)

### ISSUE THREAD

**Issue by ptomato** [tc39/proposal-temporal#1685]
While reviewing #1667 I discovered that the spec text is not consistent in what kind of _options_ parameter is passed to calendar operations, when the options are intended to be the default. (I thought we consistently passed ! OrdinaryObjectCreate(**null**) for default options, but that's not the case.) These values are observable by user-defined calendars.

[DateFromFields](https://tc39.es/proposal-temporal/#sec-temporal-datefromfields):
- options parameter is not marked as optional, but it is omitted at several call sites, this is a bug either way
- PlainYearMonth.until - omitted at two call sites
- PlainYearMonth.since - omitted at two call sites

[YearMonthFromFields](https://tc39.es/proposal-temporal/#sec-temporal-yearmonthfromfields):
- PlainDate.toPlainYearMonth - passes **undefined**
- PlainDateTime.toPlainYearMonth - passes **undefined**
- ZonedDateTime.toPlainYearMonth - passes **undefined**
- ToTemporalYearMonth, [second call site](https://tc39.es/proposal-temporal/#_ref_1319) - passes ! OrdinaryObjectCreate(**null**)

[MonthDayFromFields](https://tc39.es/proposal-temporal/#sec-temporal-monthdayfromfields):
- PlainDate.toPlainMonthDay - passes **undefined**
- PlainDateTime.toPlainMonthDay - passes **undefined**
- ZonedDateTime.toPlainMonthDay - passes **undefined**
- ToTemporalMonthDay, [second call site](https://tc39.es/proposal-temporal/#_ref_1388) - passes ! OrdinaryObjectCreate(**null**)

[CalendarDateAdd](https://tc39.es/proposal-temporal/#sec-temporal-calendardateadd):
- BuiltInTimeZoneGetInstantFor, via AddDateTime - passes ! OrdinaryObjectCreate(**null**) ([on my recommendation having been unaware of this issue](https://github.com/tc39/proposal-temporal/pull/1667))
- AddZonedDateTime (indirectly called from ZonedDateTime.round, ZonedDateTime.until, ZonedDateTime.since, Duration.add, Duration.subtract, Duration.round) - passes ! OrdinaryObjectCreate(**null**)
- UnbalanceDurationRelative (indirectly called from Duration.compare, Duration.round, Duration.total) - passes ! OrdinaryObjectCreate(**null**)
- BalanceDurationRelative (indirectly called from Duration.round) - passes ! OrdinaryObjectCreate(**null**)
- AddDuration (indirectly called from Duration.add, Duration.subtract, Duration.round) - passes ! OrdinaryObjectCreate(**null**)
- MoveRelativeDate (indirectly called from Duration.compare, Duration.round, Duration.total, PlainDate.until/since, PlainDateTime.until/since, ZonedDateTime.until/since, PlainYearMonth.until/since) - passes ! OrdinaryObjectCreate(**null**)
- RoundDuration (indirectly called from Duration.round, Duration.total, PlainDate.until/since, PlainDateTime.until/since, ZonedDateTime.until/since, PlainYearMonth.until/since) - passes ! OrdinaryObjectCreate(**null**)

[CalendarDateUntil](https://tc39.es/proposal-temporal/#sec-temporal-calendardateuntil):
- always called with non-default options from within Temporal

Any opinion on which is preferable? I had been preferring ! OrdinaryObjectCreate(**null**) for consistency because it was pre-existing and I wasn't aware of this issue. But if we have to choose, it seems like **undefined** would be easier for implementations to optimize in the case of a built-in calendar.

**Comment by ljharb** [comment]
I agree passing undefined wherever it’d be observable seems like the best choice. User calendars can use defaulting or optional chaining to trivially bypass the difference.
