### ISSUE TITLE
Validate Intl.DateTimeFormat & toLocaleString spec-text

### ISSUE THREAD

**Issue by pipobscure** [tc39/proposal-temporal#169]

**Comment by sffc** [comment]
@Ms2ger 

See the outstanding comments on the first PR for guidance on what needs to be done here.

I wanted to discuss a bit more regarding the default enabled fields for Temporal types.  I realized that if we enable *all* fields, then the "optional" fields like era, weekday, and dayPeriod will also be enabled.  I propose doing something like the following table:

| Pattern | Allowed Fields | Default Fields |
|---|---|---|
| TemporalDatePattern | year, month, day, era, weekday | year, month, day |
| TemporalYearMonthPattern | year, month, era | year, month |
| TemporalMonthDayPattern | month, day | month, day |
| TemporalTimePattern | hour, minute, second, (dayPeriod), (fractionalSecondDigits) | hour, minute, second |
| TemporalDateTimePattern | *everything* | year, month, day, hour, minute, second |
| TemporalAbsolutePattern | *everything* | year, month, day, hour, minute, second |

Question regarding the types that have time: should we include fractionalSecondDigits by default?  If we set that option to include the full precision supported by these types (nanoseconds), that would be too wide for the common case.  I would suggest not including fractionalSecondDigits by default but allowing users to request it manually.

**Comment by pipobscure** [comment]
I also suggest not having fractional seconds on by default. Your table is exactly what I was hoping for.

**Comment by sffc** [comment]
There are not as many open comments as I had originally thought, but there are still editorial issues.

**Comment by littledan** [comment]
Does #465 fix this issue, or are there more things to address?

**Comment by sffc** [comment]
This part of the spec will likely need to be reworked in the new calendar world.  Closing as obsolete.
