### ISSUE TITLE
Add "resolver" in a later proposal?

### ISSUE THREAD

**Issue by Turbo87** [tc39/proposal-temporal#17]
To keep the API surface area small for the initial proposal it might make sense to choose a reasonable default for the `resolver` option, but not make it configurable for now. Since it is part of the `options` object it looks reasonable to add it to the spec at a later point, the only downside would be that it's not clear how to figure out if your native implementation of the classes support the resolver or not, and it might be a little harder to polyfill.

**Comment by maggiepint** [comment]
Yes, we were thinking of bumping this one off to later and just defining a default behavior.

**Comment by mj1856** [comment]
We've removed resolvers from the current proposal, at least as far as construction goes.  We've left room for an `options` object on `localDateTime.withZone`, which could potentially include a resolver function.  The default most certainly will be `forwardShifted` and `firstOccurrence`.  It's just whether or not it makes sense to allow them to be changed.

**Comment by ryzokuken** [comment]
Closing this since it’s beyond the scope of this proposal and thus isn’t really actionable. You can check all the deferred issues by going to https://github.com/tc39/proposal-temporal/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Adeferred.
