### ISSUE TITLE
Order of  If Type(item) is not Object, throw in PlainMonthDay and PlainYearMonth toPlainDate

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/proposal-temporal#1702]
Two methods almost have the same operations in
https://tc39.es/proposal-temporal/#sec-temporal.plainmonthday.prototype.toplaindate
https://tc39.es/proposal-temporal/#sec-temporal.plainyearmonth.prototype.toplaindate

I would really love to refactor it to some common function either in the spec or in my v8 implementation.
However, right now I cannot because the place to perform  If Type(item) is not Object, throw is different. 
But I see no practical reason it need to be. This is observable so I cannot just change the order.
Could we make a Normative change to move  such check from step 6 to step 3? so later we can refactor them?

10.3.12 Temporal.PlainMonthDay.prototype.toPlainDate ( item )

@ptomato

**Comment by ptomato** [comment]
Sounds good, I don't see why this order should be different.
