### ISSUE TITLE
Date.difference no-op code

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-temporal#173]
`days + 1` doesn't do anything - not that it's reachable, because `month` is a `ReferenceError`.

https://github.com/tc39/proposal-temporal/blob/95bdd5bad02ff4e2677947a468a0d2bb4577ab78/polyfill/lib/date.mjs#L88-L89

**Comment by pipobscure** [comment]
This was very buggy. Fixed and tests added for all date/time maths
