### ISSUE TITLE
specify return value of null in GetIANATimeZone*Transition 

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/proposal-temporal#1764]
The caller of GetIANATimeZoneNextTransition and GetIANATimeZonePreviousTransition
https://tc39.es/proposal-temporal/#sec-temporal.timezone.prototype.getnexttransition
```
5. Let transition be ? GetIANATimeZoneNextTransition(startingPoint.[[Nanoseconds]], timeZone.[[Identifier]]).
6. If transition is null, return null.
```
https://tc39.es/proposal-temporal/#sec-temporal.timezone.prototype.getprevioustransition
```
5. Let transition be ? GetIANATimeZonePreviousTransition(startingPoint.[[Nanoseconds]], timeZone.[[Identifier]]).
6. If transition is null, return null.
```

However, the descriptions of these two AOs didn't mention they will return null but only mention it will return "an integer representing the number of nanoseconds....". I think we need to add more text to the description of these two AOs to specify what condition will return null .

https://tc39.es/proposal-temporal/#sec-temporal-getianatimezonenexttransition
11.6.6 GetIANATimeZoneNextTransition ( epochNanoseconds, timeZoneIdentifier )
The abstract operation GetIANATimeZoneNextTransition is an implementation-defined algorithm that returns an integer representing the number of nanoseconds since the Unix epoch in UTC that corresponds to the first time zone transition after epochNanoseconds in the IANA time zone identified by timeZoneIdentifier.

11.6.7 GetIANATimeZonePreviousTransition ( epochNanoseconds, timeZoneIdentifier )
The abstract operation GetIANATimeZonePreviousTransition is an implementation-defined algorithm that returns an integer representing the number of nanoseconds since the Unix epoch in UTC that corresponds to the last time zone transition before epochNanoseconds in the IANA time zone identified by timeZoneIdentifier.

@ptomato @sffc @ljharb @Ms2ger @anba @ryzokuken @justingrant

**Comment by ptomato** [comment]
I agree, these should say something like "or **null** if no such transition exists".
