### ISSUE TITLE
undefined in Temporal.Duration.prototype.total 

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/proposal-temporal#1773]
Don't know how to implement 
7.3.21 Temporal.Duration.prototype.total ( options )
https://tc39.es/proposal-temporal/#sec-temporal.duration.prototype.total
```
6. Let unbalanceResult be ? UnbalanceDurationRelative(duration.[[Years]], duration.[[Months]], duration.[[Weeks]], duration.[[Days]], unit, relativeTo).
```
then...
```
9. Let balanceResult be ? BalanceDuration(unbalanceResult.[[Days]], unbalanceResult.[[Hours]], unbalanceResult.[[Minutes]], unbalanceResult.[[Seconds]], unbalanceResult.[[Milliseconds]], unbalanceResult.[[Microseconds]], unbalanceResult.[[Nanoseconds]], unit, intermediate).
```

But UnbalanceDurationRelative only return 
```
13. Return the Record { [[Years]]: years, [[Months]]: months, [[Weeks]]: weeks, [[Days]]: days }.
```
see https://tc39.es/proposal-temporal/#sec-temporal-unbalancedurationrelative
so  unbalanceResult.[[Hours]], unbalanceResult.[[Minutes]], unbalanceResult.[[Seconds]], unbalanceResult.[[Milliseconds]], unbalanceResult.[[Microseconds]], unbalanceResult.[[Nanoseconds]], will all be undefined.

@ptomato @justingrant @Ms2ger @ryzokuken @ljharb 
I think I caught another related to Duration on balance in a different PR but this ia different one I thnk

**Comment by ptomato** [comment]
Fixed by #1779.
