### ISSUE TITLE
Add more `calendar: 'gregory'` coverage to Test262 tests and/or demitasse tests

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#1776]
This issue follows up on #1768 where @ptomato had a good idea: use existing ISO tests to cover non-ISO code by using `calendar: 'gregory'` which returns the same results (if `year > 1`) but executes the non-ISO polyfill code. 

For datemath.mjs tests, using both calendars was super-easy. But we have hundreds of other tests which could probably leverage the same trick, both in demitasse and Test262.  This is a tracking issue for this suggestion.

Notes:

* From https://github.com/tc39/proposal-temporal/issues/1768#issue-978419717:
> When converting the tests to test262, we should ensure that the iso8601 tests are added to built-ins/Temporal/Calendar but the gregory tests are added to intl402/Temporal/Calendar in test262. 
* Could adding gregory support to these tests be automated, either using codegen as a one-time thing and/or doing like datemath.mjs where both calendars are used?

**Comment by ptomato** [comment]
I'll add this to https://github.com/tc39/test262/issues/3002.
