### ISSUE TITLE
Review Date.plus/minus, disambiguation handling

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-temporal#178]
Filing to think about this some more.

Example to consider: 2019-01-31 + P1M

**Comment by pipobscure** [comment]
That's precisely the issue:

constrain(2019-01-31 + P1M) => 2019-02-28
balance(2019-01-31 + P1M) => 2019-03-03
reject(2010-01-31 + P1M) => 2019-02-31 throw error

**Comment by ryzokuken** [comment]
Closing this since disambiguation is already handled properly in `Date.plus` and `Date.minus`. Feel free to reopen if I seem to be missing something there.
