### ISSUE TITLE
start of week in calendars

### ISSUE THREAD

**Issue by always-maap** [tc39/proposal-temporal#1787]
Hey. I'm writing a blog around locales and calendars in Temporal. I notice a difference between the implementation of [temporal-polyfill](https://github.com/js-temporal/temporal-polyfill) and other JS date libs like [dayjs](https://github.com/iamkun/dayjs), [date-fns](https://github.com/date-fns/date-fns).
The start day of the week of a lot of countries is 'Monday' or 'Saturday'. 
`Temporal.Now.plainDate('persian').dayOfWeek` is would be wrong in this case for local calendar. I think you guys are aware of this but I want to know more to if there is a particular reason I mention it in my blog.

https://github.com/date-fns/date-fns/blob/master/src/locale/fa-IR/index.js#L23
https://github.com/iamkun/dayjs/blob/dev/src/locale/fa.js#L9

Thanks

**Comment by FrankYFTang** [comment]
> @justingrant aha I get it now. thanks a lot

Intl Locale info is now "stage" in Chrome . - which mean you can turn it on to access it in a start up flag but most users won't see it.
There is a separated issue related to week (which day is weekend- Burnie has Friday and Sunday- but not Saturday as weekend which make our current design not good enough.) need a redesign of the return so we will not launch it until we fullly address that spec change. Likley  you will see it got launch in Chrome around early next year.
