### ISSUE TITLE
ToTemporalTimeRecord requires all fields, but they are not necessary for PlainDate / PlainTime

### ISSUE THREAD

**Issue by Constellation** [tc39/proposal-temporal#1803]
When running the code, which comes from the document (https://tc39.es/proposal-temporal/docs/plaintime.html#from)

```
time = Temporal.PlainTime.from({ hour: 19, minute: 39, second: 9 }); // => 19:39:09
```

We run `ToTemporalTime` from `Temporal.PlainTime.from`. https://tc39.es/proposal-temporal/#sec-temporal.plaintime.from
And then `ToTemporalTime` runs `ToTemporalTimeRecord` in step 3-f. https://tc39.es/proposal-temporal/#sec-temporal-totemporaltime

However, `ToTemporalTimeRecord` requires that all time properties are defined.
> b. Let value be ? Get(temporalTimeLike, property).
> c. If value is undefined, then
>     i. Throw a TypeError exception.

Thus, the example code in the document throws RangeError since `millisecond`, `microsecond`, and `nanosecond` properties are undefined.

I think intended behavior is using zero for non-defined fields (except for day and month, they should be 1), so I think this is a spec issue (not a document's issue).

**Comment by ptomato** [comment]
I agree, this not intended and is a normative change that should be made.
