### ISSUE TITLE
Is Time.fromString supposed to allow a date part

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-temporal#184]
```js
const yearpart = /(?:[+-]\d{6}|\d{4})/;
const datepart = new RegExp(`(?:${yearpart.source}-\\d{2}-\\d{2})`);
const timepart = /(?:\d{2}\:\d{2}(?:\:\d{2}(?:\.\d{3}(?:\d{3}(?:\d{3})?)?)?)?)/;
const zonepart = /(?:Z|(?:[+-]\d{1,2}\:?\d{2}(?:\[[^\]\s]+\])?))/;
export const time = new RegExp(`^(?:${datepart.source}T)?${timesplit.source}(?:${zonepart.source})?$`);
```

**Comment by pipobscure** [comment]
I’d say yes. Reason: consistency.

Since we don’t have a combined type for good reasons, we need from string to support partial extraction on DateTime & TimeZone, so you can retain the full meaning in an ISO string that has all parts. If DateTime & TimeZone can do it, then so should Date & Time.
