### ISSUE TITLE
Fix docs invariant for `until` and `since`

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#1877]
The [docs for `PlainDate.p.since`](https://tc39.es/proposal-temporal/docs/plaindate.html#since) say:

> The returned `Temporal.Duration`, when subtracted from `date` using the same `options`, will yield `other`.

This is wrong because options no longer overlap between `add`/`subtract` and `until`/`since`. Should be something like this:

> The returned `Temporal.Duration`, when subtracted from `date` will yield `other` as long as both of the following are true:
> * The call to `since` does not round the duration, either because it uses the default options for `smallestUnit` and `roundingIncrement`, or because the duration has only zero values for units that otherwise would have been rounded.
> * The call to `subtract` uses the default `overflow: 'constrain'` options.

The problem shows up everywhere `until` and `since` are documented.

**Comment by HERBOD7** [comment]
Dear @ptomato can I do it?

**Comment by justingrant** [comment]
Yes! PRs are welcomed. Thanks!
