### ISSUE TITLE
Verify that modulo and remainder are only called on mathematical values

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#1887]
While looking for other problems with modulo, I saw methods that didn't assert or coerce input to be mathematical values. The spec may be doing the right thing upstream, but sometime before the Dec plenary, we should verify that all usage of modulo and remainder are only called on mathematical values.  

While we're at it, maybe check other built-in mathematical operations (min, max, abs, floor) too?

Feel free to close this issue if this scrub has already been done. 

- [x] modulo
- [x] remainder
- [x] min
- [x] max
- [x] abs
- [x] floor

**Comment by ptomato** [comment]
All of the instances that @Ms2ger identified have been fixed, except for https://github.com/tc39/ecma402/issues/619 which we'll either get when rebasing onto a newer ECMA-402, or will be fixed in ECMA-402 after Temporal reaches Stage 4. I think this can be closed now.
