### ISSUE TITLE
Specify the order in List return by GetIANATimeZoneEpochValue

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/proposal-temporal#1898]
GetIANATimeZoneEpochValue may return 0, 1, or 2 epoch. In Oct 2021 meeting, Shane lead a discussion about the order in list and many people express the desire for all return list to specify the order to avoid future compatibility issue. Therefore, I think when GetIANATimeZoneEpochValue return more than one item, the spec text need to specify the order of those item return

https://tc39.es/proposal-temporal/#sec-temporal-getianatimezoneepochvalue

@sffc @justingrant @ljharb

**Comment by gibson042** [comment]
This was resolved by #2161: https://github.com/tc39/proposal-temporal/commit/e6a15a5e2426f3bc808c8592fbd8a6149d833a8e#diff-f75a130313fadc1f7ea7dd49d0f0309dd65ec3ab698097e1d89b2c39a49a7b5cL468-R482
```diff
-        When the input represents a local time repeating multiple times at a negative time zone transition (e.g. when the daylight saving time ends or the time zone offset is decreased due to a time zone rule change), the returned List will have more than one element.
+        When the input represents a local time repeating multiple times at a negative time zone transition (e.g. when the daylight saving time ends or the time zone offset is decreased due to a time zone rule change), the returned List will have more than one element. The elements are sorted in numerical order.
```
