### ISSUE TITLE
In `until` & `since`, should `roundingIncrement` & `roundingMode` options be allowed when `smallestUnit` is undefined?

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#1900]
Currently we allow code like this: 

```js
Temporal.PlainTime.from('10:00').since('09:30:59.999999999', { roundingIncrement: 5, roundingMode: 'halfExpand' })
// => PT29M
Temporal.PlainTime.from('10:00').since('09:30:59.999999999')
// => PT29M0.000000001S
```

It's almost certain that the first line of code above is a programmer bug, where the bug is forgetting to specify a `smallestUnit`. The most likely reason would be if the caller expects the default `smallestUnit` to be seconds or milliseconds or whatever their favorite other platform uses as a default rounding unit.

Should we disallow this case, for the same reason that `smallestUnit` is required for the `round` method, because the default rounding unit varies across platforms and cannot be inferred?  The reason why `smallestUnit` is optional in `until`/`since` is because we wanted the default behavior to be "no rounding", but once the user is asking for rounding then it seems reasonable to require similar expectations as in `round`.

"Disallow" could mean that `smallestUnit` would be required if a non-undefined value is provided for `roundingIncrement` and/or `roundingMode` options.

**Comment by ptomato** [comment]
Per the Temporal champions meeting of 2022-01-06, we decided this is not important enough to change in Stage 3, since either interpretation is valid depending on the mental model of the programmer. Additionally, NumberFormat sets a precedent of always ignoring well-formed but unused options.
