### ISSUE TITLE
Incorrect use of remainder() in GetISOPartsFromEpoch?

### ISSUE THREAD

**Issue by linusg** [tc39/proposal-temporal#1927]
I'm not quite sure about this, but I found that my implementation of the current spec yields incorrect results for GetISOPartsFromEpoch with negative epochNanoseconds.

*Not quite sure* because it was changed from plain `modulo` to `remainder()` recently, with a note of the former being incorrect and adding plenty of tests to validate a correct implementation:

- https://github.com/tc39/proposal-temporal/commit/baaa8fd1ab0e24f9b1e5b9f64f66e1385753c3ec

  ```diff
  - 1. Let remainderNs be epochNanoseconds modulo 10⁶.
  + 1. Let remainderNs be the mathematical value whose sign is the sign of epochNanoseconds and whose magnitude is abs(epochNanoseconds) modulo 10⁶.
  ```
- https://github.com/tc39/proposal-temporal/commit/b7bdc653de58fc101db03d7819c55d2a216957e1

  ```diff
  - 1. Let remainderNs be the mathematical value whose sign is the sign of epochNanoseconds and whose magnitude is abs(epochNanoseconds) modulo 10⁶.
  + 1. Let remainderNs be remainder(epochNanoseconds, 10⁶).
  ```

Let's take `-13849764_999_999_999n` as an example, which is commonly used in the provided tests. The only AO using `GetISOPartsFromEpoch` is `BuiltinTimeZoneGetPlainDateTimeFor`, which in turn plenty of `ZonedDateTime` prototype functions use - let's take `toString()` for simplicity.

The result I'm getting is:

```js
new Temporal.ZonedDateTime(-13849764_999_999_999n, new Temporal.TimeZone("UTC")).toString() === "1969-07-24T16:50:35.001000001+00:00[UTC]"
```

whereas the polyfill (correctly) does this:

```js
new Temporal.ZonedDateTime(-13849764_999_999_999n, new Temporal.TimeZone("UTC")).toString() === "1969-07-24T16:50:35.000000001+00:00[UTC]"
```

notice how `milliseconds` is 1 but expected to be 0.

Let's do the AO step by step, using -13849764999999999 as mentioned above:

> 1. Assert: epochNanoseconds is an integer.

sure, -13849764999999999 passes that assertion.

> 2. Let remainderNs be remainder(epochNanoseconds, 10⁶).

Given `remainder(x, y)` is defined as `mathematical value whose sign is the sign of x and whose magnitude is abs(x) modulo y.`, we get:

`remainderNs` = `-(abs(-13849764999999999) modulo 1000000)` = `-(13849764999999999 modulo 1000000)` = `-999999`.

> 3. Let epochMilliseconds be (epochNanoseconds − remainderNs) / 10⁶.

`epochMilliseconds` = `(-13849764999999999 - (-999999)) / 1000000` = `-13849764999000000 / 1000000` = `-13849764999`

> 4. Let year be ! YearFromTime(epochMilliseconds).
> 5. Let month be ! MonthFromTime(epochMilliseconds) + 1.
> 6. Let day be ! DateFromTime(epochMilliseconds).
> 7. Let hour be ! HourFromTime(epochMilliseconds).
> 8. Let minute be ! MinFromTime(epochMilliseconds).
> 9. Let second be ! SecFromTime(epochMilliseconds).

These all yield correct results, and are not affected by the last three digits of `epochMilliseconds` (the actual milliseconds part, which changes in step 2 + 3 if modulo is used).

> 10. Let millisecond be ! msFromTime(epochMilliseconds).

Given `msFromTime(t) = 𝔽(ℝ(t) modulo msPerSecond)` and `msPerSecond = 1000𝔽`, we get:

`millisecond` = `-13849764999 modulo 1000` = `1`

Now, this is obviously unexpected, as the actual millisecond value for going back in time by 999999999 nanoseconds should be 0.

> 11. Let microsecond be floor(remainderNs / 1000) modulo 1000.

`microsecond` = `floor(-999999 / 1000) modulo 1000` = `floor(-999.999) modulo 1000` = `-1000 modulo 1000` = `0`

Different value for `remainderNs` than expected, still correct by chance.

> 12. Let nanosecond be remainderNs modulo 1000.

`nanosecond` = `-999999 modulo 1000` = `1`

Different value for `remainderNs` than expected, still correct by chance.

---

Had we performed `modulo` instead of `remainder()` in step 2, we'd get:

> 2. Let remainderNs be epochNanoseconds modulo 10⁶.

`remainderNs` = `-13849764999999999 modulo 1000000` = `1`

> 3. Let epochMilliseconds be (epochNanoseconds − remainderNs) / 10⁶.

`epochMilliseconds` = `(-13849764999999999 - 1) / 1000000` = `-13849765000000000 / 1000000` = `-13849765000`

> 4. to 9.

Identical results.

> 10. Let millisecond be ! msFromTime(epochMilliseconds).

`millisecond` = `-13849765000 modulo 1000` = `0`

Correct this time!

> 11. Let microsecond be floor(remainderNs / 1000) modulo 1000.

`microsecond` = `floor(1 / 1000) modulo 1000` = `floor(0.001) modulo 1000` = `0 modulo 1000` = `0`

> 12. Let nanosecond be remainderNs modulo 1000.

`nanosecond` = `1 modulo 1000` = `1`

---

Does this make sense? Do we need to go back to modulo as per the previous spec or am I missing something?

**Comment by ptomato** [comment]
I'm afraid you're right. Probably what confused me is that `BigInteger.divmod()` performs remainder(), but then we add some [extra code](https://github.com/tc39/proposal-temporal/blob/60c753a6369c0a61cacc353562214aaa6327117a/polyfill/lib/ecmascript.mjs#L2242-L2245) in the polyfill to make the result equal to performing modulo.
