### ISSUE TITLE
Polyfill vs. spec mismatch in PrepareTemporalFields

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#1963]
The spec for [PrepareTemporalFields](https://tc39.es/proposal-temporal/#sec-temporal-preparetemporalfields) says:

> 1. Assert: Type(fields) is Object.

But the polyfill for this AO treats non-`Object` values as OK.

```js
  PrepareTemporalFields: (bag, fields) => {
    if (ES.Type(bag) !== 'Object') return false;
```

Why does the polyfill accept a non-`Object` parameter without throwing while the spec says that that a non-`Object` parameter is disallowed?

I assume this is a bug, but wanted to make sure before PR-ing a change. And assuming it's a bug, I assume that the spec is correct but the polyfill is wrong?

Tracking the git blame on this change was fun because this AO has changed its name many times, but looks like this `return false` case was introduced in #346 by @ptomato when the name of the AO was `ValidDateTimeFrom`, which then was changed to `ToRecord`, and which finally ended up as `PrepareTemporalFields`.  At least that's what I think the provenance was! 🤷‍♂️ 

BTW this was exposed by the TS work that @jens-ox is doing over in https://github.com/js-temporal/temporal-polyfill/pull/103 to remove unexpected `undefined`s from the TS codebase.

**Comment by ptomato** [comment]
We discussed this today, it seems easy enough to change the code and see if anything breaks. Due to the spec not accepting Object here, the change seems to me like it should be correct.
