### ISSUE TITLE
Temporal.TimeZone() no longer canonicalizes numeric UTC offset [[Identifier]]

### ISSUE THREAD

**Issue by linusg** [tc39/proposal-temporal#2007]
https://github.com/tc39/proposal-temporal/commit/75490b98069feb9758bd0830c4ae3be149aa2bba wasn't purely editorial, it has an observable change - since `FormatTimeZoneOffsetString` is no longer being called, and `CreateTemporalTimeZone` directly uses the passed argument for `[[Identifier]]`, no canonicalization is performed for (valid) *TimeZoneNumericUTCOffset* strings like `+01`, `-0123` etc.

Previously, the `id` property would contain the canonicalized variant of the input string.

This is tested in https://github.com/tc39/test262/blob/e87b0048c402479df1d9cb391fb86620cf3200fd/test/built-ins/Temporal/TimeZone/basic.js#L10-L24 for example, which breaks when implemented as per the latest spec revision.

**Comment by ptomato** [comment]
Oops! I wrote that mistakenly thinking that [[Identifier]] and [[OffsetNanoseconds]] were mutually exclusive. I think we can fix this by changing 

3. Set _object_.[[Identifier]] to _identifier_.
4. If _identifier_ satisfies the syntax of a _TimeZoneNumericUTCOffset_ (see 13.32), then
    a. Set _object_.[[OffsetNanoseconds]] to ! ParseTimeZoneOffsetString(_identifier_).
5. Else,
    a. Assert: ! CanonicalizeTimeZoneName(_identifier_) is _identifier_.
    b. Set _object_.[[OffsetNanoseconds]] to **undefined**.

to something like this

3. Let _offsetNanoseconds_ be ParseTimeZoneOffsetString(_identifier_).
4. If _offsetNanoseconds_ is an abrupt completion, then
    a. Assert: ! CanonicalizeTimeZoneName(_identifier_) is _identifier_.
    b. Set _object_.[[Identifier]] to _identifier_.
    c. Set _object_.[[OffsetNanoseconds]] to **undefined**.
5. Else,
    a. Set _object_.[[Identifier]] to ! FormatTimeZoneOffsetString(_offsetNanoseconds_).
    b. Set _object_.[[OffsetNanoseconds]] to _offsetNanoseconds_.

Or, we could make [[Identifier]] and [[OffsetNanoseconds]] actually mutually exclusive, and just do FormatTimeZoneOffsetString in Temporal.TimeZone.prototype.toString.
