### ISSUE TITLE
ToTemporalYearMonth/ParseTemporalYearMonthString implementation inconsistent between spec and polyfill

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-temporal#2016]
The text removed in 5a65ade9b74627891ceddef66fe4f9b6b4321cb2 (#1525) remained in the polyfill. It seems like it might be used here still, because ParseTemporalYearMonthString doesn't always fill in the `referenceISODay` field. I believe none of this is observable, since only built-in calendars can be created from a string. I think it's worthwhile to keep them more in sync, though, or at least add a note to the polyfill.

**Comment by ptomato** [comment]
I'd have to take a closer look, but at least if I remove that code from the polyfill no tests fail.
