### ISSUE TITLE
"Date Duration Record" in the 2nd paragraph of 7.5.3 Time Duration should be "Time Duration Record"

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/proposal-temporal#2128]
In https://tc39.es/proposal-temporal/#sec-temporal-time-duration-records

the link after "Table 7" is incorrect:
"
7.5.3 Time Duration [Record](https://tc39.es/ecma262/#sec-list-and-record-specification-type)s
A Time Duration Record is a Record value used to represent the portion of a Temporal.Duration object that deals with exact time units. Time Duration Records are produced by the abstract operation [CreateTimeDurationRecord](https://tc39.es/proposal-temporal/#sec-temporal-createtimedurationrecord), among others.

Of the fields listed in [Table 7](https://tc39.es/proposal-temporal/#table-temporal-duration-record-fields), **[Date Duration Records](https://tc39.es/proposal-temporal/#sec-temporal-date-duration-records)** have [[Days]], [[Hours]], [[Minutes]], [[Seconds]], [[Milliseconds]], [[Microseconds]], and [[Nanoseconds]].
"

It should be (both the text and the link) "Time Duration Record", right?

**Comment by ptomato** [comment]
Someone fixed this already at some point.
