### ISSUE TITLE
Docs: `TimeZone.getNext...`/`...PreviousTransition()` are not only about DST

### ISSUE THREAD

**Issue by h-h-h-h** [tc39/proposal-temporal#2137]
https://tc39.es/proposal-temporal/docs/ambiguity.html says:

> Offsets can also change permanently due to political changes, e.g. a country switching time zones.

Therefore, the description for [`TimeZone.getNextTransition()`](https://tc39.es/proposal-temporal/docs/timezone.html#getNextTransition) and `TimeZone.getPreviousTransition()` should not just talk about DST. Currently, it only points to DST over and over:

> startingPoint [...]: Time after which to **find the next DST transition.**
>
> Returns: A Temporal.Instant object **representing the next DST transition in this time zone**, or null if no transitions later than startingPoint could be found.
>
> **This method is used to calculate future DST transitions** after startingPoint for this time zone.
>
> Note that if the time zone was constructed from a UTC offset, there will be no **DST transitions**. In that case, this method will return null.

This gives a wrong impression and could lead to transitions being labeled as DST switches in software that's written using Temporal, even though some transitions aren't DST switches.

**Comment by ptomato** [comment]
Closed by #2138.
