### ISSUE TITLE
Fix disambiguation handling in TimeZone.p.getAbsoluteFor

### ISSUE THREAD

**Issue by ryzokuken** [tc39/proposal-temporal#217]
The handling of the `disambiguation` parameter in `TimeZone.prototype.getAbsoluteFor` is somewhat weird, there's a line like:

```js
if (!~['earlier', 'later'].indexOf(disambiguation)) throw new RangeError(`no such absolute found`);
```

which isn't exactly required since the `switch` statement's default case is:

```js
      default:
        throw new RangeError(`no such absolute found`);
```

@pipobscure is this on purpose? Should I feel free to refactor this?

**Comment by pipobscure** [comment]
It's a cheap check to avoid the GetTimeZoneOffsetMilliseconds operations that aren't necessary.
