### ISSUE TITLE
Syntax checking spec text is too sloppy

### ISSUE THREAD

**Issue by gibson042** [tc39/proposal-temporal#2186]
The spec contains many uses of "_{satisfy,satisfies,adheres to,…} the syntax of \<grammar nonterminal>_", often followed by something like "_\<String value> contains \<grammar nonterminal>_". These should all be replaced with formal use of ParseText and the Parse Nodes it returns upon success.

**Comment by ptomato** [comment]
I did a quick search and I think this has already been completed as part of other editorial improvements.
