### ISSUE TITLE
ISO 8601 grammar uses incorrect separating punctuation

### ISSUE THREAD

**Issue by gibson042** [tc39/proposal-temporal#2190]
The ISO 8601 grammar currently separates nonterminals from their productions with `:`, but that is only appropriate for the [ECMAScript syntactic grammar](https://tc39.es/ecma262/multipage/notational-conventions.html#sec-syntactic-grammar) (which has as its terminal symbols "_ECMAScript tokens defined by the lexical grammar_"). Grammars which have Unicode code points as their terminal symbols use either `::` ([Lexical and RegExp grammars](https://tc39.es/ecma262/multipage/notational-conventions.html#sec-lexical-and-regexp-grammars), which "_share some productions_") or `:::` ([Numeric String grammar](https://tc39.es/ecma262/multipage/notational-conventions.html#sec-numeric-string-grammar) and [URI grammar](https://tc39.es/ecma262/multipage/global-object.html#sec-uri-syntax-and-semantics), both of which incorporate nonterminals from the lexical grammar).

I'm not sure what the distinction between `::` vs. `:::` is intended to represent, but absent guidance from @tc39/ecma262-editors I have a gut feeling that `:::` is slightly more appropriate because both the URI and ISO 8601 grammars relate to external specifications.

**Comment by ptomato** [comment]
I asked and @bakkot answered:

> `:::` is for the grammar used for parsing strings to numbers in like +'10', I mean, not when parsing actual number literals. It's never used when actually parsing source text.
> `:` is for translating tokens to parse nodes, `::` is for translating code points to tokens (or regexes, I guess)

Based on that, I'd guess `:::` is appropriate for the ISO 8601 grammar.
