### ISSUE TITLE
Consistent verification of overflow options?

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-temporal#2220]
E.g. `PlainDate.from` goes out of its way to call `ToTemporalOverflow` if the argument is already a `PlainDate`, but then it calls `ToTemporalDate`, which has fast paths for `ZonedDateTime` and `PlainDateTime` which don't call `ToTemporalOverflow`. Is this intentional?

**Comment by ptomato** [comment]
This is probably not intentional. I think we need to check it in the fast paths, but not in the CalendarDateFromFields path since _options_ is passed directly to dateFromFields.
