### ISSUE TITLE
Rewrite DurationHoursPart, DurationMinutesPart, and DurationSecondsPart grammar to avoid extra checks for fractional parts

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2282]
This is the current grammar:

> DurationSecondsPart :
> &emsp; DurationWholeSeconds DurationSecondsFraction<sub>opt</sub> SecondsDesignator
> > 
> DurationMinutesPart :
> &emsp; DurationWholeMinutes DurationMinutesFraction<sub>opt</sub> MinutesDesignator DurationSecondsPart<sub>opt</sub>
> 
> DurationHoursPart :
> &emsp; DurationWholeHours DurationHoursFraction<sub>opt</sub> HoursDesignator DurationMinutesPart
> &emsp; DurationWholeHours DurationHoursFraction<sub>opt</sub> HoursDesignator DurationSecondsPart<sub>opt</sub>

We should check whether it's valid to rewrite it to:

> DurationSecondsPart :
> &emsp; DurationWholeSeconds DurationSecondsFraction<sub>opt</sub> SecondsDesignator
> 
> DurationMinutesPart :
> &emsp; DurationWholeMinutes DurationMinutesFraction MinutesDesignator
> &emsp; DurationWholeMinutes MinutesDesignator DurationSecondsPart<sub>opt</sub>
> 
> DurationHoursPart :
> &emsp; DurationWholeHours DurationHoursFraction HoursDesignator
> &emsp; DurationWholeHours HoursDesignator DurationMinutesPart
> &emsp; DurationWholeHours HoursDesignator DurationSecondsPart<sub>opt</sub>

That would allow to remove the extra checks for fractional parts in [ParseTemporalDurationString](https://tc39.es/proposal-temporal/#sec-temporal-parsetemporaldurationstring):
> 9. If fHours is not empty, then
>    a. If any of minutes, fMinutes, seconds, fSeconds is not empty, throw a RangeError exception.
>    b. [....]
> 10.  [....]
> 11. If fMinutes is not empty, then
>     a. If any of seconds, fSeconds is not empty, throw a RangeError exception.
>    b. [....]

**Comment by ptomato** [comment]
I believe this is valid, yes.
