### ISSUE TITLE
Review MakeDay/MakeDate/TimeFromYear callers for possibly out-of-range values

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2315]
From #1502:
> `MakeDate` can return NaN for large year values, because `MakeDay` has wishy-washy definition when NaN can be returned for large values:
> > [...], but if this is not possible (because some argument is out of range), return NaN.

There are multiple `MakeDay`, `MakeDate`, and `TimeFromYear` callers which simply assert the returned value is finite, but this may not be true in practice. For example consider calling [GetEpochFromISOParts](https://tc39.es/proposal-temporal/#sec-temporal-getepochfromisoparts) with `GetEpochFromISOParts(Number.MAX_VALUE, 1, 1, 0, 0, 0, 0, 0, 0)`.

Also see: https://github.com/tc39/ecma262/issues/1087 and https://github.com/tc39/ecma262/pull/1564

**Comment by ptomato** [comment]
From the duplicate #2396, this is one code sample that would have MakeDay return NaN:
```js
var cal = new Temporal.Calendar("iso8601");
var date = new Temporal.PlainDate(1970, 1, 1);
var maxValue = new Temporal.Duration(Number.MAX_VALUE, Number.MAX_VALUE);
cal.dateAdd(date, maxValue)
```
This ends up calling MakeDay(𝔽(ℝ(Number.MAX_VALUE) + 1970), 0, 1) in AddISODate → BalanceISODate, and that year value is not finite.
