### ISSUE TITLE
BalanceDurationRelative, largestUnit="year": Is it correct to set `relativeTo` when the loops in steps 10.d and 10.h haven't been entered?

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2341]
[BalanceDurationRelative](https://tc39.es/proposal-temporal/#sec-temporal-balancedurationrelative):
> <ol start=10>
> <li> If largestUnit is "year", then
>   <ol type=a>
>     <li> Let moveResult be ? MoveRelativeDate(calendar, relativeTo, oneYear).
>     <li> <b>Set relativeTo to moveResult.[[RelativeTo]].</b>
>     <li> Let oneYearDays be moveResult.[[Days]].
>     <li> Repeat, while abs(days) ≥ abs(oneYearDays),
>       <ol type=i>
>         <li> Set days to days - oneYearDays.
>         <li> Set years to years + sign.
>         <li> Set moveResult to ? MoveRelativeDate(calendar, relativeTo, oneYear).
>         <li> <b>Set relativeTo to moveResult.[[RelativeTo]].</b>
>         <li> Set oneYearDays to moveResult.[[Days]].
 </ol></ol></ol>

`relativeTo` is updated even when the loop isn't (re-)entered in step 10.d. (Also applies to step 10.h.)

This seems wrong, because it can affect `oneMonthDays` when the old `relativeTo` is in a leap year and the current month is February.

Test case:
```js
// Note: February in a leap year.
let date = new Temporal.PlainDate(1972, 2, 1);

let options = {
  largestUnit: "years",
  relativeTo: date,
};

// Prints "P3Y11M27D"
console.log(Temporal.Duration.from({years: 3, months: 11, days: 27}).round(options).toString());

// Prints "P4Y"
console.log(Temporal.Duration.from({years: 3, months: 11, days: 28}).round(options).toString());
```

The spec polyfill doesn't seem to update `relativeTo` right away, because it prints "P3Y11M28D" instead of "P4Y".

**Comment by ptomato** [comment]
Agreed, it looks like the spec text is out of sync here with the algorithm we have in the polyfill which it was based upon.
