### ISSUE TITLE
Bikeshedding the name of the inZone method

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-temporal#235]
Now that we have `Temporal.TimeZone`, should we call this method `inTimeZone`?

**Comment by ryzokuken** [comment]
In a quick albeit shallow search of the codebase (unfortunately the search functionality in VSCode doesn't allow negative lookahead), I failed to come up with the usage of "zone" anywhere apart from timezones, so +1 to this.

**Comment by maggiepint** [comment]
No opposition, especially if it creates API parity.

**Comment by ryzokuken** [comment]
@pipobscure do you have any contradicting opinions on this by any chance? Assigning this to myself, will make a PR for it today.
