### ISSUE TITLE
Are ZDT docs wrong about subtraction order of operations?

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#2358]
I just noticed this content in the [ZonedDateTime docs](https://tc39.es/proposal-temporal/docs/zoneddatetime.html#add): 

> * Addition (or subtraction of a negative duration) is performed in order from largest unit to smallest unit.
> * Subtraction (or addition of a negative duration) is performed in order from smallest unit to largest unit.

Is this correct?  My (admittedly fuzzy, it's been a while) memory is that we both add and subtract largest units first.

**Comment by ptomato** [comment]
There's no difference in order of operations between addition and subtraction, so this documentation is wrong.

Both of the lines are actually wrong. We add and subtract (larger) calendar units before (smaller) time units, but there is no particular order enforced within each of those groupings.

For calendar units, the ISO calendar is specified to add/subtract years, months, then weeks and days together, so roughly largest to smallest. We don't specify the other built-in calendars (although I guess at least the Gregorian-based ones would do the same as ISO), and a custom calendar's `dateAdd` method is of course free to do whatever order it wants.

For time units, it's exact time, so the addition or subtraction is performed simultaneously for all units.

Concretely, I think it's sufficient to remove those two lines from the docs. We could add a line that calendar units are added/subtracted before time units.
