### ISSUE TITLE
The specification text should use SpeciesConstructor for methods like plus

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-temporal#239]
This is part of implementing subclassing support #196. The polyfill seems to implement this well, e.g., https://github.com/tc39/proposal-temporal/blob/main/polyfill/lib/date.mjs#L86 . However, the spec text still calls things like CreateDate directly, e.g., in Temporal.Date.prototype.plus

**Comment by ptomato** [comment]
This was done by Ms2ger some time ago.
