### ISSUE TITLE
Precision may bring back keystroke timing attacks?

### ISSUE THREAD

**Issue by Vasile-Peste** [tc39/proposal-temporal#2399]
I see that this comes with a precision up to nanoseconds.

In the past, the precision of [performance.now() Reduced time precision](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now#reduced_time_precision) API has been reduced drastically up to milliseconds.

A sophisticated timing attack can be performed by creating a timer, and the more precise the timer is, the more effective the attack can be, which can result in creating a pseudokeylogger working outside of the browser tab and process.

I'm wondering if this precision could bring back this kind of attack.

Paper: [Practical Keystroke Timing Attacks in Sandboxed JavaScript](https://mlq.me/download/keystroke_js.pdf)

**Comment by ptomato** [comment]
Good question. The presence of `microsecond` and `nanosecond` properties in Temporal, and the ability to add and subtract microsecond and nanosecond durations, doesn't require browsers to expose any more precision than they do in other APIs. So, if a browser decides they want to provide 1 ms precision for security reasons, e.g. `Temporal.Now.zonedDateTime()` would return an object where `microsecond` and `nanosecond` are always 0.
