### ISSUE TITLE
ZonedDateTime.from documentation is missing the `timeZone` property

### ISSUE THREAD

**Issue by bergus** [tc39/proposal-temporal#2426]
https://tc39.es/proposal-temporal/docs/zoneddatetime.html#from:

> If the value is any other object, a `Temporal.ZonedDateTime` will be constructed from the values of any `year` (or `era` and `eraYear`), `month` (or `monthCode`), `day`, `hour`, `minute`, `second`, `millisecond`, `microsecond`, `nanosecond`, and/or `calendar` properties that are present.
> At least the `timeZone`, `year` (or `era` and `eraYear`), `month` (or `monthCode`), and `day` properties must be present.

The first sentence does not mention  the `timeZone` property, the second says it's required.

**Comment by justingrant** [comment]
Hi @bergus - thanks for catching this mistake. If you want to file a PR on the [docs](https://github.com/tc39/proposal-temporal/blob/main/docs/zoneddatetime.md) to fix this, it will be gratefully welcome!
