### ISSUE TITLE
Planetary Body Offset

### ISSUE THREAD

**Issue by JKeddo95** [tc39/proposal-temporal#2512]
Hi all. Have any of the implementer given thought to including an optional/skippable "planetTimeOffsetRatio" offset capability? Javascript will probably be around for at least another 20-30 years -- At that point in the far future, it wouldn't be that crazy to start thinking about "Moon time" or "Mars time". Considering those bodies have variable length days, we could optionally give users the chance to track time with time-timezone-date-calendar-***planetTimeOffsetRatio***. 

For example, If the calendar planetTimeOffsetRatio is 1.02777778 (Mars:Earth days), the number of seconds in a Mars day would be shortened by 2.777778% to get Earth time. This idea could scale to the moon and other planets as well. What are you guy's thoughts?

**Comment by justingrant** [comment]
Sorry, Temporal's initial release is not planning to support non-24hr days use cases, including: calculations that take leap seconds into account; non-terrestrial days; and far-past terrestrial days (earth's rotation was faster billions of years ago).

Feel free to open an issue for future Temporal-related proposals here: https://github.com/js-temporal/proposal-temporal-v2.
