### ISSUE TITLE
DifferenceISODate: Avoid using different aliases for the same variable values

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2526]
[DifferenceISODate](https://tc39.es/proposal-temporal/#sec-temporal-differenceisodate) should consistently use either the input arguments `{y,m,d}1` and `{y,m,d}2` or the corresponding record values from `start` and `end`. For examples current steps 1.e-g:
> e. Let years be end.[[Year]] - start.[[Year]].
> f. Let mid be ! [AddISODate](https://tc39.es/proposal-temporal/#sec-temporal-addisodate)(y1, m1, d1, years, 0, 0, 0, "constrain").
> g. Let midSign be -(! [CompareISODate](https://tc39.es/proposal-temporal/#sec-temporal-compareisodate)(mid.[[Year]], mid.[[Month]], mid.[[Day]], y2, m2, d2)).

Should use either:
> e. Let years be y2 - y1.
> f. Let mid be ! [AddISODate](https://tc39.es/proposal-temporal/#sec-temporal-addisodate)(y1, m1, d1, years, 0, 0, 0, "constrain").
> g. Let midSign be -(! [CompareISODate](https://tc39.es/proposal-temporal/#sec-temporal-compareisodate)(mid.[[Year]], mid.[[Month]], mid.[[Day]], y2, m2, d2)).

Or alternatively:
> e. Let years be end.[[Year]] - start.[[Year]].
> f. Let mid be ! [AddISODate](https://tc39.es/proposal-temporal/#sec-temporal-addisodate)(start.[[Year]], start.[[Month]], start.[[Day]], years, 0, 0, 0, "constrain").
> g. Let midSign be -(! [CompareISODate](https://tc39.es/proposal-temporal/#sec-temporal-compareisodate)(mid.[[Year]], mid.[[Month]], mid.[[Day]], end.[[Year]], end.[[Month]], end.[[Day]])).

**Comment by ptomato** [comment]
This was addressed by #2762.
