### ISSUE TITLE
Duplicate calendar fields in CalendarFields/PrepareTemporalFields

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2532]
When PrepareTemporalFields is preceded by MergeLists, duplicate property names are removed. When there's no MergeLists call, duplicate property names are possible, because CalendarFields itself doesn't remove duplicates. And duplicates are also possible when additional property names are added after CalendarFields, for example in ToRelativeTemporalObject when `"timeZone"` and `"offset"` are added. 

Does it make sense to skip over duplicates in PrepareTemporalFields? It's cheap to handle duplicates in PrepareTemporalFields, because `sortedFieldNames` is already sorted, so all duplicate property names are adjacent to each other and therefore can be detected easily.

MergeLists is then also no longer needed and can be replaced with [list-concatenation](https://tc39.es/ecma262/#list-concatenation).

**Comment by gibson042** [comment]
We like this suggestion.
