### ISSUE TITLE
RejectObjectWithCalendarOrTimeZone: Avoid "Reject" so there's no confusion about Promise rejection?

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2534]
"Reject" is exclusively used for Promise rejection in ECMA-262. Should "Reject" be replaced with a different verb in "RejectObjectWithCalendarOrTimeZone"?

For example compare to [RejectPromise](https://tc39.es/ecma262/#sec-rejectpromise), which unconditionally rejects a Promise, whereas "RejectObjectWithCalendarOrTimeZone" conditionally throws an error.

**Comment by gibson042** [comment]
One possibility is refactoring into something like HasCalendarOrTimeZone or IsTemporalLikeObject and constructing errors at the call site when it returns true, which would seem like an improvement.
