### ISSUE TITLE
CalendarEquals, ConsolidateCalendars, and TimeZoneEquals are called with String values, too

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2550]
CalendarEquals, ConsolidateCalendars, and TimeZoneEquals are now called with String values, too. The structured header needs to be updated to reflect this change.

And step 1 should be more precise what happens when either value is a String.
> 1. If one and two are the same Object value, return true.

**Comment by ptomato** [comment]
I'll update the structured headers, but what do you suggest changing about when either value is a String? If they are not the same Object value, then they both get processed by ToTemporalCalendarIdentifier.
