### ISSUE TITLE
CalendarFields returns Array instead of List for string calendars

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2551]
[CalendarFields](https://tc39.es/proposal-temporal/#sec-temporal-calendarfields) should add the step:
> 1.c. Return ! CreateListFromArrayLike(array, « String »).

(`CreateListFromArrayLike` instead of `IterableToListOfType` to match the fast path in [GetPossibleInstantsFor](https://tc39.es/proposal-temporal/#sec-temporal-getpossibleinstantsfor)).

---

Also: When step 1.b. calls `%Temporal.Calendar.prototype.fields%`, there's still an observable Array iteration, see [step 4](https://tc39.es/proposal-temporal/#sec-temporal.calendar.prototype.fields). Do we want to resp. can we avoid the array iteration here? For example we could add a ListIteratorObject which is a spec-internal, not user-observable object which implements the iterator protocol. So when `%Temporal.Calendar.prototype.fields%` is called with that ListIteratorObject, the iteration is unobservable.

Or alternatively just inline `%Temporal.Calendar.prototype.fields%` into `CalendarFields`:

> 1. If calendar is a String, then
>     a. Return fieldNames.

Or with ECMA-402:
> 1. If calendar is a String, then
>   a. If calendar is "iso8601", then
>       &emsp;i. Return fieldNames.
>   b. Return CalendarDateFields(calendar, fieldNames).

**Comment by justingrant** [comment]
Meeting 2023-04-13: The part of this issue above the "line" was a bug in the spec text of #2482 that wasn't caught before that PR was merged a few days ago, so we'll treat it as if it were a review comment on that PR and fix it now.

For the part of this issue below the line, we believe that #2519 should address this issue.
