### ISSUE TITLE
ObjectImplementsTemporalCalendarProtocol: Excessive checks of properties?

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2552]
[ObjectImplementsTemporalCalendarProtocol](https://tc39.es/proposal-temporal/#sec-temporal-objectimplementstemporalcalendarprotocol) currently checks all properties which are called in the various Calendar* abstract operations. For example:
- `"dateAdd"` because of CalendarDateAdd
- `"dateFromFields"` because of CalendarDateFromFields
- `"dateUntil"` because of CalendarDateUntil
- `"day"` because of CalendarDay
- etc.

This seems (a) a bit excessive and (b) seems problematic for forward compatibility. When a future proposal adds, let's say [CalendarWeeksInYear](https://github.com/js-temporal/proposal-temporal-v2/issues/8) and a corresponding `Temporal.Calendar.prototype.weeksInYear` function, does that mean `ObjectImplementsTemporalCalendarProtocol` needs to check the property key `"weeksInYear"`, too? If yes, does that mean that custom calendars will suddenly stop working when an implementation adds support for `Temporal.Calendar.prototype.weeksInYear`, because [ToTemporalCalendarSlotValue](https://tc39.es/proposal-temporal/#sec-temporal-totemporalcalendarslotvalue) will start throwing a TypeError if `"weeksInYear"` is absent?

Also applies to [ObjectImplementsTemporalTimeZoneProtocol](https://tc39.es/proposal-temporal/#sec-temporal-objectimplementstemporaltimezoneprotocol).

---

Kind of related:
[IsRegExp](https://tc39.es/ecma262/#sec-isregexp) tests for a single property to classify an object as RegExp-like. This special behaviour of `Symbol.match` isn't liked by all (https://github.com/tc39/ecma262/pull/1318). There used to be a `Symbol.isRegExp` well-known symbol to mark an object as RegExp-like. It was replaced with `Symbol.match` in ES6 draft rev29 per the [resolution from the Nov 2014 meeting](https://github.com/tc39/notes/blob/main/meetings/2014-11/nov-18.md#410-regexp-subclassing-fixes).

**Comment by justingrant** [comment]
> This seems (a) a bit excessive and (b) seems problematic for forward compatibility

Meeting 2023-04-13: We'll leave the current behavior as-is. The reasoning is that userland code forgetting to implement a method in a custom time zone or custom calendar will probably be a common bug, so it's helpful to catch that bug early (when objects are constructed using that calendar or time zone) as opposed to crashing at some later time. 

This is a different case from something like RegExp where userland developers are not realistically expected to build them, even if the spec allows this.

re: (b), the set of methods being checked will never be expanded in a later edition of the spec. Future editions will have to allow ay new properties to be undefined. 

re: (a), our understanding was the `HasProperty` check is both low-cost (relative to what a calendar or time zone object is actually doing) and is only observable if the object is a Proxy or has one in its prototype chain. Furthermore, this check is only done when objects are first introduced, e.g. when a ZDT object is created or when a property-bag `relativeTo` option is interpreted. Subsequent usage won't trigger the check. Furthermore, in the optimized case (which we expect to be used 90%+ of the time) of using strings for IDs, this check won't be triggered at all. For these reasons, we thought that this extra cost was worth it in exchange for early detection of userland bugs. If you (or anyone else) find any cases in the spec where the assumptions in this paragraph are not true, please let us know!

That said, we'll keep this issue open to add a note(s) in the spec to explain the following:
  * Explain the reason to check every property (to make it easier to catch bugs in custom calendars/timezones)
  * Indicate that future editions must never add more properties to the "required" list and must tolerate undefined properties for newly-added properties
