### ISSUE TITLE
Review all typeof === "object" checks in the polyfill

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-temporal#256]
Because `typeof null === "object"`

**Comment by littledan** [comment]
Probably we should be doing RequireObjectCoercible for many of these checks, and for other ones, checking for `typeof x === "string"` first.

**Comment by Ms2ger** [comment]
That's a spec question we could probably discuss; this issue is about incorrect implementations of `Type(x) == Object` checks in the spec.

**Comment by littledan** [comment]
I think we should basically never check Type(x) == Object--this is not something that the JS spec does. Let's fix the spec issue first, rather than aligning the polyfill to a strange specification.

**Comment by ljharb** [comment]
The JS spec does that quite often; however if the user’s passing in an object bag (something 262 has no precedent for) it might make more sense to use RequireObjectCoercible/ToObject.

**Comment by littledan** [comment]
I guess I meant, in ordinary functions as opposed to primitive operations like +. Yes, you are right, there are several cases of this check.

**Comment by littledan** [comment]
Looks like `typeof obj === "object"` checks are still all over the polyfill, so it might make sense to take a look here.

**Comment by Ms2ger** [comment]
Note: `Type(x) = Object` also covers things whose `typeof` is `"function"`; use `ES.Type(..) === "Object"`instead
