### ISSUE TITLE
Polyfill: should we replace numeric regex indexes with constants?

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#2560]
From @12wrigja in  https://github.com/js-temporal/temporal-polyfill/pull/244/files#r1169131944: 

> it does strike me as odd that all the magic indices for match groups for regexes are littered across the codebase. Maybe it would be nicer to define these as constants in regex.ts with useful names and import them in to improve readability?

Normally I'd not bother doing this here in the proposal repo polyfill, but it does seem that using friendlier names might make it more self-documenting for implementers looking at the polyfill code.

Although we'd need to check whether are there some cases where the same number has different meanings depending on the string? Would want to make sure that using names instead of numbers would make things better not worse.

**Comment by ljharb** [comment]
Isn't the polyfill code going to be deleted once normative changes stop, or at least prior to archival? I don't think implementers *should* be looking at an implementation here, that's what the spec text is for.
