### ISSUE TITLE
Calendar fields can include `constructor` and `__proto__`

### ISSUE THREAD

**Issue by ljharb** [tc39/proposal-temporal#2576]
It seems that currently a calendar's `fields` method can return a list that includes `constructor` and/or `__proto__`. 

I can't think of any use case where these two properties *should* be calendar fields. If not, should we ban them? It might avoid a class of prototype pollution vulnerabilities as well.

**Comment by justingrant** [comment]
Meeting 2023-08-17: This was fixed in #2570. Closing.
