### ISSUE TITLE
TimeZoneIANAName grammar productions are too restrictive

### ISSUE THREAD

**Issue by gibson042** [tc39/proposal-temporal#2608]
[|TimeZoneIANAName|](https://tc39.es/proposal-temporal/#prod-TimeZoneIANAName) is _syntactically_ limited to the union of non-legacy names (which do not include `+` or ASCII digits) and legacy names (which are limited to the union of a list of 8 specific exceptions and those of the form "Etc/GMT±\<unpadded hour>"). This diverges from the [IXDTF draft](https://www.ietf.org/archive/id/draft-ietf-sedate-datetime-extended-08.html#section-4.1), which allows each slash-separated component to end with an arbitrary combination of ASCII letters, digits, and `.`/`_`/`+`/`-` punctuation (e.g., "2023-06-14T15:25Z[Foo/Bar+1]"). Temporal should follow suit, allowing rejection of such input to be handled _semantically_ in e.g. [ToTemporalTimeZoneSlotValue](https://tc39.es/proposal-temporal/#sec-temporal-totemporaltimezoneslotvalue) when GetAvailableNamedTimeZoneIdentifier returns <tt>empty</tt>.

Note that IXDTF might also be updated to drop the 14-character length restriction on components (cf. https://github.com/ietf-wg-sedate/draft-ietf-sedate-datetime-extended/issues/46 ), in which case Temporal should adopt that change as well.

**UPDATE**: The length restriction was dropped in https://github.com/ietf-wg-sedate/draft-ietf-sedate-datetime-extended/pull/50 .

**Comment by justingrant** [comment]
Meeting 2023-08-17: We'll make this change. It's an editorial change because invalid identifiers already throw a RangeError in all cases affected by this change. @gibson042 will make a PR for this.
