### ISSUE TITLE
AddDurationToOrSubtractDurationFromPlainYearMonth: Check for string calendars before calling GetMethod

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2619]
Step 12:
> Let dateAdd be ? [GetMethod](https://tc39.es/ecma262/#sec-getmethod)(calendar, "dateAdd").

But `calendar` can be a String calendar.

**Comment by ptomato** [comment]
Thanks for the report. This is similar to #2547. I will subsume this issue into https://github.com/tc39/proposal-temporal/pull/2519#discussion_r1166146921 because I already need to check for string calendars there.
