### ISSUE TITLE
Accept fractional values in fromEpochSeconds and fromEpochMilliseconds

### ISSUE THREAD

**Issue by mcfedr** [tc39/proposal-temporal#2625]
It would be very useful for interacting with other code, if the functions `Instant.fromEpochSeconds` and `Instant.fromEpochMilliseconds` where able to accept non-integer values

Such that I could do `Instant.fromEpochSeconds(1688734354.5)`

Otherwise I'm forced to manipulate the value into a bigint number of probably nanoseconds

**Comment by ptomato** [comment]
Hi and thanks for the suggestion! We definitely cannot do this though, as non-integer numbers in JS are not exact. (1688734354.5 from your example is exact, but, for example, 1688734354.1 is not; it would give 1688734354.099999905 s). This might be worth revisiting in a follow-on proposal if JS gains an exact-decimal type.
