### ISSUE TITLE
Reorganize PrepareTemporalFields and CalendarFields abstract operations

### ISSUE THREAD

**Issue by ptomato** [tc39/proposal-temporal#2630]
Make the remaining editorial refactor described in this comment in #2570:

- We'd like to throw on duplicates returned from CalendarFields, while still preserving the fact that it's not necessarily a bug if the two invocations of `fields()` return two unique lists that have some overlap when merged.
- Every invocation of CalendarFields is always followed by PrepareTemporalFields with no observable operation in between, so it doesn't matter if we throw on duplicates at the end of CalendarFields, or after sorting at the beginning of PrepareTemporalFields. Anba has indicated that throwing after sorting in PrepareTemporalFields allows optimization by only iterating the list once.
- The problem with throwing on duplicates in PrepareTemporalFields is that although CalendarFields is always followed by PrepareTemporalFields in the current spec, there's no guarantee that CalendarFields will continue to be used correctly in the future. Replace CalendarFields with two new AOs: a simple one that returns the result of PrepareTemporalFields, and a complex one that returns a record with both the names (the result of `fields()`) and the object result of PrepareTemporalFields. This new AO would need to accept an additional List of names to be added, e.g. `*offset*` and `*timeZone*`. If adding those values creates duplicates, then throw.

_Originally posted by @ptomato in https://github.com/tc39/proposal-temporal/pull/2570#discussion_r1194493010_

**Comment by justingrant** [comment]
Meeting 2023-08-17: Philip will get to this after previously-approved normative changes are landed.
