### ISSUE TITLE
Temporal.Duration.prototype.total: Condition to convert zonedRelativeTo to plainRelativeTo incorrect

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2681]
Step 11:
> If zonedRelativeTo is not undefined; and unit is any of "year", "month", "week"; and any of duration.[[Years]], duration.[[Months]], duration.[[Weeks]] ≠ 0; then

The both conditions should be connected through "or" instead of "and", that means

> If zonedRelativeTo is not undefined; and unit is any of "year", "month", "week"; or any of duration.[[Years]], duration.[[Months]], duration.[[Weeks]] ≠ 0; then

**Comment by ptomato** [comment]
That's correct. However, this is fixed anyway in #2671 ("Normative: Precalculate PlainDateTime from ZonedDateTime in more places") so I'll leave this alone for now.
