### ISSUE TITLE
RoundDuration: Use truncate(fractionalDays) instead of truncate(days)

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2685]
Step 7.k:
> Let wholeDaysDuration be ? CreateTemporalDuration(0, 0, 0, truncate(days), 0, 0, 0, 0, 0, 0).

But `days` has already been set to zero in step 4.d. Instead the step should be:
> Let wholeDaysDuration be ? CreateTemporalDuration(0, 0, 0, truncate(fractionalDays), 0, 0, 0, 0, 0, 0).

**Comment by ptomato** [comment]
As usual, thanks for spotting this. It's probably a rebase error. It's already being fixed in #2671 (commit "Normative: Avoid calendar operations when adding days-only duration to PlainDate") so I'll leave this alone for now.
