### ISSUE TITLE
GetPlainDateTimeFor: Infallible when precalculatedOffsetNanoseconds is present

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2687]
All calls to `GetPlainDateTimeFor` are infallible when the optional `precalculatedOffsetNanoseconds` is present, but some callers are calling it as  `? GetPlainDateTimeFor(...)`.

**Comment by ptomato** [comment]
I guess this is correct if abs(_precalculatedOffsetNanoseconds_) ≤ 86,399,999,999,999 — which it is guaranteed to be if the offset ns comes from GetOffsetNanosecondsFor. We should probably add an assertion to GetPlainDateTimeFor.
