### ISSUE TITLE
Consider deduplicating into IsCalendarUnit

### ISSUE THREAD

**Issue by ptomato** [tc39/proposal-temporal#2692]
After #2519 and #2612 there will be many instances of "If _unit_ is **"year"**, or _unit_ is **"month"**, or _unit_ is **"week"**, ..."

Consider refactoring this into an abstract operation, which could be called IsCalendarUnit. This should make several long lines in the spec more readable, as well as improve readability in the reference code.

Thanks to @Mrashes for the suggestion.

**Comment by Mrashes** [comment]
@ptomato opened a [PR](https://github.com/tc39/proposal-temporal/pull/2707) to merge.  No rush as Its for after the others are merged.
