### ISSUE TITLE
UnbalanceDateDurationRelative: Incorrect `largestUnit is "day"` assertion

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2695]
UnbalanceDateDurationRelative, step 13:
> Assert: largestUnit is "day".

This assertion is incorrect, `largestUnit` can be any unit except `"year"`, `"month"`, and `"week"`.

**Comment by ptomato** [comment]
Agreed. Somehow I thought we were setting it to "day" if it was smaller than "day" for this operation. Thanks for catching it!
I think it's best probably just to remove that step.
