### ISSUE TITLE
AddDuration: Unnecessary call to GetPlainDateTimeFor

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2696]
AddDuration only needs to call GetPlainDateTimeFor when calendar units are present. Current steps 10-11 can be rewritten as follows:

> 10. If precalculatedPlainDateTime is undefined and largestUnit is one of "year", "month", "week", or "day", then
>     1. Let startDateTime be ? GetPlainDateTimeFor(timeZone, zonedRelativeTo.[[Nanoseconds]], calendar).
> 11. Else,
>     1. Let startDateTime be precalculatedPlainDateTime.

When `largestUnit` is smaller than `"day"`, all calendar units (`{y,mon,w,d}{1,2}`) are zero, so the two AddZonedDateTime calls will take the AddInstant fast path and no `Temporal.PlainDateTime` object is needed.

**Comment by ptomato** [comment]
Thanks for spotting, as usual! I'll add a fix for this one on to part 4 (#2519).
