### ISSUE TITLE
DisambiguatePossibleInstants: earlierDateTime and laterDateTime use different calendars

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2701]
DisambiguatePossibleInstants, 19.c creates `earlierDateTime` with the ISO-8601 calendar, whereas step 23 creates `laterDateTime` using `dateTime.[[Calendar]]`.

**Comment by ptomato** [comment]
My bad, this was a rebase error in 1ff91a9730ace0af31177afab5c57bc343a5ab2f, thanks for spotting it.
