### ISSUE TITLE
NanosecondsToDays: Initial `days` computation can likely be simplified

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2703]
It should be possible to simplify NanosecondsToDays, steps 10-23 to just:
> 10. Let date1 be ! CreateTemporalDate(startDateTime.[[ISOYear]], startDateTime.[[ISOMonth]], startDateTime.[[ISODay]], "iso8601").
> 11. Let date2 be ! CreateTemporalDate(endDateTime.[[ISOYear]], endDateTime.[[ISOMonth]], endDateTime.[[ISODay]], "iso8601").
> 12. Let days be DaysUntil(date1, date2).
> 13. Let timeSign be CompareTemporalTime(startDateTime.[[ISOHour]], startDateTime.[[ISOMinute]], startDateTime.[[ISOSecond]], startDateTime.[[ISOMillisecond]], startDateTime.[[ISOMicrosecond]], startDateTime.[[ISONanosecond]], endDateTime.[[ISOHour]], endDateTime.[[ISOMinute]], endDateTime.[[ISOSecond]], endDateTime.[[ISOMillisecond]], endDateTime.[[ISOMicrosecond]], endDateTime.[[ISONanosecond]]).
> 14. If days > 0 and timeSign > 0, then
>     a. Set days to days - 1.
> 15. Else if days < 0 and timeSign < 0, then
>     a. Set days to days + 1.

**Comment by ptomato** [comment]
This is a very nice simplification. I think I've sufficiently convinced myself that it's correct, but another pair of eyes couldn't hurt. Anyway, thanks for the suggestion!
