### ISSUE TITLE
DifferenceTemporalZonedDateTime: precalculatedPlainDateTime can be calculated unconditionally

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2704]
DifferenceTemporalZonedDateTime step 9 ensures that the fast path in DifferenceZonedDateTime won't be taken:
> 9. If zonedDateTime.[[Nanoseconds]] = other.[[Nanoseconds]], then return ...

That means DifferenceZonedDateTime will always need to call GetPlainDateTimeFor and therefore the GetPlainDateTimeFor can be performed already in DifferenceTemporalZonedDateTime. 

DifferenceTemporalZonedDateTime, steps 11-14 can therefore be simplified to just:

> 11. Let instant be ! CreateTemporalInstant(zonedDateTime.[[Nanoseconds]]).
> 12. Let precalculatedPlainDateTime be ? GetPlainDateTimeFor(zonedDateTime.[[TimeZone]], instant, zonedDateTime.[[Calendar]]).
> 13. Let plainRelativeTo be ! CreateTemporalDate(precalculatedPlainDateTime.[[ISOYear]], precalculatedPlainDateTime.[[ISOMonth]], precalculatedPlainDateTime.[[ISODay]], zonedDateTime.[[Calendar]]).

**Comment by ptomato** [comment]
Right again. Miraculously, this is still an editorial change. Either the calculation is done just previous to calling DifferenceZonedDateTime, or right at the beginning of DifferenceZonedDateTime, so user code can't tell the difference if we move it to be unconditionally just prior to calling DifferenceZonedDateTime.
