### ISSUE TITLE
Temporal.Duration.prototype.round: AdjustRoundedDurationDays called with precalculatedPlainDateTime=undefined

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2705]
Temporal.Duration.prototype.round, step 37.a calls AdjustRoundedDurationDays with `precalculatedPlainDateTime`, but `precalculatedPlainDateTime` can be `undefined`, which isn't allowed by AdjustRoundedDurationDays.

**Comment by ptomato** [comment]
Yes. I'll add an assertion that it may only be undefined if we take the fast path.
