### ISSUE TITLE
Documentation states `Temporal.Duration` constructor accepts decimal numbers

### ISSUE THREAD

**Issue by meduzen** [tc39/proposal-temporal#2711]
According to the documentation of the `Temporal.Duration` constructor:

> all non-integer numerical arguments are rounded to the nearest integer, towards zero.

https://github.com/tc39/proposal-temporal/blob/3f82e8d48d3c062d07a4ae77dc175d65cc3be8ae/docs/duration.md?plain=1#L57

However, if I properly understand, [the spec says decimal values are not allowed](https://tc39.es/proposal-temporal/#sec-temporal.duration): parameters must be normalized using the abstract function [`ToIntegerIfIntegral`](https://tc39.es/proposal-temporal/#sec-tointegerifintegral), itself checking if the value is an integral number (abstraction [`IsIntegralNumber`](https://tc39.es/ecma262/#sec-isintegralnumber)), which returns `false` when it’s a decimal (step 3 of the algorithm).

As a result, it seems not correct to me when I read

> all non-integer numerical arguments are rounded to the nearest integer, towards zero.

because nothing is _rounded_: at best, some values are _converted_ (`true` to `1`, `null` to `0`…), but decimals are not allowed (I wish they would because it would have removed a bunch of computation the JS engine could leverage 😅).

The polyfill follows the spec behaviors as it throws `RangeError: unsupported fractional value 1.5` if I use `1.5` as one of the parameters, so I guess the only faulty part is the documentation (or my own understanding).

**Comment by ptomato** [comment]
That's correct, this is a mistake in the documentation. Most likely I forgot to update it when we made this change.
