### ISSUE TITLE
InterpretISODateTimeOffset: Duplicate assertion for "getPossibleInstantsFor"

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2731]
[InterpretISODateTimeOffset](https://tc39.es/proposal-temporal/#sec-temporal-interpretisodatetimeoffset), step 9:
> 9. [Assert](https://tc39.es/ecma262/#assert): [TimeZoneMethodsRecordHasLookedUp](https://tc39.es/proposal-temporal/#sec-temporal-timezonemethodsrecordhaslookedup)(timeZoneRec, getPossibleInstantsFor) is true.

But step 3 already asserts:
> 3. [Assert](https://tc39.es/ecma262/#assert): [TimeZoneMethodsRecordHasLookedUp](https://tc39.es/proposal-temporal/#sec-temporal-timezonemethodsrecordhaslookedup)(timeZoneRec, getPossibleInstantsFor) is true.

**Comment by ptomato** [comment]
Thanks!
