### ISSUE TITLE
Example violates best practices for cross-calendar code

### ISSUE THREAD

**Issue by mjomble** [tc39/proposal-temporal#2751]
The [roundToNearestMonth](https://github.com/tc39/proposal-temporal/blob/main/docs/cookbook/roundToNearestMonth.mjs) example in the cookbook contains code like this:

```
if (month > 12) {
  month %= 12;
  year++;
}
```

which seems to violate the [best practices](https://tc39.es/proposal-temporal/docs/calendar.html#writing-cross-calendar-code) by assuming there's always 12 months in a year.

Seems to me like it should use `.add({ months: 1 })` instead of working with the month and year numbers directly. I can submit a PR fixing this if needed.

**Comment by ptomato** [comment]
Good catch. Probably in fact it should use `.with({ day: 1 })` and then optionally `.add({ months: 1 })`. We would welcome a PR for this!
