### ISSUE TITLE
docs/duration.md claims Duration constructor supports option bag/string arguments

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-temporal#276]
It doesn't – that's `Duration.from`.

**Comment by pipobscure** [comment]
Sorry, that is a carry-over from earlier concepts. The constructor doe **NOT** support options bags, that's what we made the `.from` for.

**Comment by pipobscure** [comment]
Can we close this? (I will for now. reopen if someone thinks it should be)

**Comment by ptomato** [comment]
I think it should be reopened. It's still a defect in the docs, which I am working on a patch for.

**Comment by pipobscure** [comment]
Reopening per request by @ptomato

**Comment by ptomato** [comment]
Ah, I already reopened it myself and then closed it when my #320 got merged, I think this is all good now :smile:
