### ISSUE TITLE
CalendarMethodsRecordLookup uses Temporal.TimeZone.prototype 

### ISSUE THREAD

**Issue by shannonbooth** [tc39/proposal-temporal#2772]
https://tc39.es/proposal-temporal/#sec-temporal-calendarmethodsrecordlookup

Is using Temporal.TimeZone.prototype from step 3 onwards for getting the builtin calendar method (step 2 is using Temporal.Calendar.prototype)

This seems like a typo, and all the steps should be using the Calendar prototype.

**Comment by ptomato** [comment]
Good catch, thanks.
