### ISSUE TITLE
NormalizedTimeDurationToDays: SubtractNormalizedTimeDuration is infallible

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2777]
Step 17:
`norm = endNs - relativeResult.[[EpochNanoseconds]]`

Step 19:
`dayLengthNs = oneDayFarther.[[EpochNanoseconds]] - relativeResult.[[EpochNanoseconds]]`

Step 20:
```
oneDayLess = norm - dayLengthNs
           = (endNs - relativeResult.[[EpochNanoseconds]]) - (oneDayFarther.[[EpochNanoseconds]] - relativeResult.[[EpochNanoseconds]])
           = endNs - oneDayFarther.[[EpochNanoseconds]]
```

Step 21.a:
`norm = oneDayLess`

Step 21.b:
`relativeResult = oneDayFarther`

Step 21.d:
`oneDayFarther' = AddDaysToZonedDateTime(...)`

Step 21.e:
`dayLengthNs' = oneDayFarther'.[[EpochNanoseconds]] - relativeResult.[[EpochNanoseconds]]`

Step 21.f:
```
  norm - dayLengthNs'
=  oneDayLess - (oneDayFarther'.[[EpochNanoseconds]] - relativeResult.[[EpochNanoseconds]])
= (endNs - oneDayFarther.[[EpochNanoseconds]]) - (oneDayFarther'.[[EpochNanoseconds]] - oneDayFarther.[[EpochNanoseconds]])
= endNs - oneDayFarther'.[[EpochNanoseconds]]
```

- `endNs` and `oneDayFarther'.[[EpochNanoseconds]]` are both valid epoch nanoseconds values.
- Which means subtracting them won't exceed `maxTimeDuration`, so the call to `SubtractNormalizedTimeDuration` is infallible.

**Comment by ptomato** [comment]
Agreed with the reasoning, thanks for figuring this out.
