### ISSUE TITLE
DifferenceTemporalPlainYearMonth: Duplicate CreateDataPropertyOrThrow for "largestUnit"

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2800]
[DifferenceTemporalPlainYearMonth](https://tc39.es/proposal-temporal/#sec-temporal-differencetemporalplainyearmonth) adds "largestUnit" twice to `resolvedOptions`.

**Comment by ptomato** [comment]
Whoops. Luckily, this is on an unobservable object, so we can fix it.
