### ISSUE TITLE
DifferenceZonedDateTime: CreateTemporalDateTime is fallible

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2824]
[DifferenceZonedDateTime](https://tc39.es/proposal-temporal/#sec-temporal-differencezoneddatetime), step 12.b:
> Let intermediateDateTime be ! CreateTemporalDateTime(intermediateDate.[[Year]], intermediateDate.[[Month]], intermediateDate.[[Day]], startDateTime.[[ISOHour]], startDateTime.[[ISOMinute]], startDateTime.[[ISOSecond]], startDateTime.[[ISOMillisecond]], startDateTime.[[ISOMicrosecond]], startDateTime.[[ISONanosecond]], calendarRec.[[Receiver]]).

This call is fallible. Test case:
```js
const nsMaxInstant = 864n * 10n**19n;
const nsMinInstant = -nsMaxInstant;

const nsPerDay = 24*60*60*1000*1000*1000;

let tz = new class extends Temporal.TimeZone {
  getOffsetNanosecondsFor(instant) {
    if (instant.epochNanoseconds === nsMinInstant) {
      return 0;
    }
    return -nsPerDay + 1;
  }
}("UTC");

let zdt1 = new Temporal.ZonedDateTime(nsMinInstant, tz);
let zdt2 = new Temporal.ZonedDateTime(nsMinInstant + 1n, tz);

let d = zdt1.until(zdt2, {
  largestUnit: "days",
});

console.log(d.toString());
```

**Comment by ptomato** [comment]
This should have been fixed with #2925, creating the intermediate should no longer be fallible due to removing custom time zones. The intermediate date time could still be outside the representable range, but that will get caught by GetPossibleEpochNanoseconds.
