### ISSUE TITLE
Polyfill: Temporal.PlainDate.from treats "eraYear" as "year" for calendars without eras

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2870]
```js
Temporal.PlainDate.from({calendar: "hebrew", era: "foobar", eraYear: 1, month: 1, day: 1}).toString()
```

returns `"-003760-09-07[u-ca=hebrew]"`, but I'd expect this to throw a TypeError, because no `year` property is present. `era` and `eraYear` inputs should be completely ignored for calendar systems without eras, right? IOW `eraYear` is accepted as an input iff [CalendarDateEraYear](https://tc39.es/proposal-temporal/#sec-temporal-calendardateerayear) returns a non-`undefined` value for a specific calendar system.

**Comment by ptomato** [comment]
This seems to be an issue with the implementation-defined part of the reference code. The spec text is correct.
