### ISSUE TITLE
Temporal.Duration.prototype.round: Unnecessary check for IsCalendarUnit(smallestUnit) 

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2874]
Step 40.a:
> If calendarUnitsPresent is true, or IsCalendarUnit(largestUnit) is true, or IsCalendarUnit(smallestUnit) is true, throw a RangeError exception.

`IsCalendarUnit(largestUnit) is true` implies that `IsCalendarUnit(smallestUnit)` returns `true`, too. 

See also step 23:
> If LargerOfTwoTemporalUnits(largestUnit, smallestUnit) is not largestUnit, throw a RangeError exception.

**Comment by ptomato** [comment]
Personally I find it clearer to be explicit that both are not calendar units, but we could change _smallestUnit_ to an assertion?
