### ISSUE TITLE
Consistent argument order for "timeZoneRec" and "calendarRec"

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2876]
Previously the spec consistently used the argument order `timeZoneRec` followed by `calendarRec`, but the new operations from:
- https://github.com/tc39/proposal-temporal/commit/e47a3f618fb1079c135bf3f0258d01c1869b921d
- https://github.com/tc39/proposal-temporal/commit/b373f21b425bf8ad0cdaf2554ceb58f033d21ec2

uses the reverse argument order (i.e. first `calendarRec` and then `timeZoneRec`). The argument order should be made consistent throughout the spec.

**Comment by ptomato** [comment]
This would still apply if we removed custom calendars, but would be _timeZone_ and _calendar_ instead of _timeZoneRec_ and _calendarRec_. For rebasing reasons let's revisit this after it's clear whether that's going to land.
