### ISSUE TITLE
DifferenceZonedDateTimeWithRounding: precalculatedPlainDateTime can be undefined

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2878]
`precalculatedPlainDateTime` can be `undefined` when called from `Temporal.Duration.prototype.{round,total}`.

**Comment by ptomato** [comment]
I'd like to revisit this after it's clear whether there is agreement to remove custom calendars. If there are no user hooks, there is no reason to have _precalculatedPlainDateTime_ either.

**Comment by ptomato** [comment]
Obsoleted by #2925.
