### ISSUE TITLE
Temporal.Duration.prototype.total: Unnecessary assertion for roundRecord.[[Total]] not being UNSET

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2879]
Step 21:
> 21. Assert: roundRecord.[[Total]] is not unset.

`roundRecord` when returned from DifferenceZonedDateTimeWithRounding and DifferencePlainDateTimeWithRounding are spec'ed to return a mathematical value in `[[Total]]`. RoundTimeDuration doesn't explicitly mention that `[[Total]]` is a mathematical value, but it's easy to see that `total` is a mathematical value, too. 

If RoundRelativeDuration when called from DifferenceZonedDateTimeWithRounding and DifferencePlainDateTimeWithRounding can set `[[Total]]` to `UNSET`, then DifferenceZonedDateTimeWithRounding and DifferencePlainDateTimeWithRounding either need to be changed to allow returning `[[Total]]: UNSET` or assert that `[[Total]]` isn't `UNSET`.

**Comment by ptomato** [comment]
Yes, DifferenceZonedDateTimeWithRounding should be changed to allow `UNSET`. [[Total]] cannot be `UNSET` when _largestUnit_ and _smallestUnit_ are the same unit, as when calling `total()`, but you can get the NudgeToZonedTime path when calling `round()`.

As far as I know, DifferencePlainDateTimeWithRounding should not be able to return with [[Total]] `UNSET`.
