### ISSUE TITLE
NudgeToCalendarUnit: Wrong roundedSign for (roundedUnit - total == 0)?

### ISSUE THREAD

**Issue by woess** [tc39/proposal-temporal#2893]
**[NudgeToCalendarUnit](https://tc39.es/proposal-temporal/#sec-temporal-nudgetocalendarunit)** step 16 says:
>
_12. Let progress be (destEpochNs - startEpochNs) / (endEpochNs - startEpochNs)._
_13. Let total be r1 + progress × increment × sign._
_15. Let roundedUnit be ApplyUnsignedRoundingMode(total, r1, r2, unsignedRoundingMode)._
**16. If roundedUnit - total < 0, let roundedSign be -1; else let roundedSign be 1.**
_17. If roundedSign = sign, then_
_&emsp; a. Let didExpandCalendarUnit be true._
_&emsp; b. Let resultDuration be endDuration._
_&emsp; c. Let nudgedEpochNs be endEpochNs._

If `progress == 0`, and therefore `total == r1` and `roundedUnit - total == 0`, `roundedSign` would be 1, which I believe is wrong if sign == 1, because it would then pick _endDuration_ rather than _startDuration_.

This case is covered by test262 [`test/built-ins/Temporal/PlainDate/prototype/until/smallestunit-higher-units.js`](https://github.com/tc39/test262/blob/a15874163e6a4f19ee7cd3e47592af382af0f5fd/test/built-ins/Temporal/PlainDate/prototype/until/smallestunit-higher-units.js#L22-L24):
```
const earlier = Temporal.PlainDate.from("2019-01-08");
const later = Temporal.PlainDate.from("2021-09-07");

TemporalHelpers.assertDuration(
  earlier.until(later, { smallestUnit: "weeks", roundingMode: "halfExpand" }),
  0, 0, /* weeks = */ 139, 0, 0, 0, 0, 0, 0, 0, "weeks");
```

IIUC, as currently specified, this would incorrectly round up to 140 weeks.

Note that the [polyfill](https://github.com/tc39/proposal-temporal/blob/82ad54fa251f32f03720fe5aef5d2e9af208d42b/polyfill/lib/ecmascript.mjs#L3925) just uses `Math.sign` here:
```
const didExpandCalendarUnit = MathSign(roundedUnit - total) === sign;
```

So perhaps it should be specified that way, too? i.e. like this (or equivalent):
_16. If roundedUnit - total < 0, let roundedSign be -1; else if roundedUnit - total > 0, let roundedSign be 1; else let roundedSign be 0._

**Comment by ptomato** [comment]
Thanks for the report.
