### ISSUE TITLE
NudgeToDayOrTime: Incorrect assertion in step 1

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2897]
Step 1:
> Assert: The value in the "Category" column of the row of Table 22 whose "Singular" column contains smallestUnit, is time.

`smallestUnit` can be `"day"`, whose Category in <https://tc39.es/proposal-temporal/#table-temporal-units> is `DATE`.

**Comment by ptomato** [comment]
Closed in #2922, forgot to auto-link.
