### ISSUE TITLE
ZonedDateTime.from() / .with() overflow option default

### ISSUE THREAD

**Issue by chrisveness** [tc39/proposal-temporal#2909]
In ZonedDateTime.from(), the overflow option apparently defaults to constrain (rather than reject).

The effect of this is to silently update parameters without warning. This seems unfriendly behaviour, and a likely foot-gun.

I encountered this in the following context:

````
const t1 = Temporal.Instant.from('2024-03-31T23:45Z').toZonedDateTimeISO('UTC');
const t2 = t1.with({ hour: 24, minute: 0, second: 0 });
console.log(t2.toString());
````

I was anticipating a resulting time of midnight (or otherwise an error), and was very surprised to find it was `2024-03-31T23:00:00+00:00[UTC]`.

I would prefer to be warned of this, and explicitly set overflow to constrain if I actually wanted such behaviour.

**Comment by ptomato** [comment]
Thanks for the feedback! We discussed this in the 2024-07-11 meeting. Yes, this is unfortunately a case where there's not one right answer, so we're going to stick with the default that we have. In one context this is unfriendly, in another it's useful: e.g. https://github.com/tc39/proposal-temporal/issues/2840#issuecomment-2114208861
