### ISSUE TITLE
ZonedDateTime.withPlainTime() Documentation

### ISSUE THREAD

**Issue by Yay295** [tc39/proposal-temporal#2917]
The documentation for `ZonedDateTime.withPlainTime()` declares that it returns a `PlainDateTime`, but says that it returns a `ZonedDateTime`.

https://github.com/tc39/proposal-temporal/blob/727211d41366390c9a56a36f1009f379bd8eb4d4/docs/zoneddatetime.md?plain=1#L757-L764

**Comment by ptomato** [comment]
Thanks for catching this. Would you like to make a PR fixing it?
