### ISSUE TITLE
NormalizedTimeDurationAbs: Inline into both callers?

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2957]
`NormalizedTimeDurationAbs` returns a Normalized Time Duration Record, but both callers directly retrieve `[[TotalNanoseconds]]` without actually using the record itself. 

Change [DifferenceTime](https://tc39.es/proposal-temporal/#sec-temporal-differencetime), step 8 from:
> 8. Assert: NormalizedTimeDurationAbs(norm).[[TotalNanoseconds]] < nsPerDay.

to:
> 8. Assert: abs(norm.[[TotalNanoseconds]]) < nsPerDay.

And [UnnormalizeDuration](https://tc39.es/proposal-temporal/#sec-temporal-unnormalizeduration), step 3 from:
> 3. Let nanoseconds be NormalizedTimeDurationAbs(normalizedDuration.[[NormalizedTime]]).[[TotalNanoseconds]].

to:
> 3. Let nanoseconds be abs(normalizedDuration.[[NormalizedTime]].[[TotalNanoseconds]]).

**Comment by ptomato** [comment]
We can just remove the assertion from DifferenceTime. The same assertion already exists at the end of NormalizeTimeDuration.
