### ISSUE TITLE
Directly access [[TotalNanoseconds]] instead of adding NormalizedTimeDurationSeconds + NormalizedTimeDurationSubseconds

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2966]
`DifferencePlainDateTimeWithRounding` and `DifferenceZonedDateTimeWithRounding` both perform:

> Let total be NormalizedTimeDurationSeconds(diff.[[NormalizedTime]]) × 10**9 + NormalizedTimeDurationSubseconds(diff.[[NormalizedTime]]).

This seems easier:

> Let total be diff.[[NormalizedTime]].[[TotalNanoseconds]].

**Comment by ptomato** [comment]
I think this is probably left over from when I thought I was still going to rewrite Normalized Time Duration in terms of two floats. Yes, the proposed language is easier.
