### ISSUE TITLE
AnnotatedTime: Early error for month-day doesn't check for parse errors

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2984]
> It is a Syntax Error if IsValidMonthDay of ParseText(Time DateTimeUTCOffset[~Z], DateSpecMonthDay) is true. 

Doesn't that imply that `IsValidMonthDay` can be called with a List of parse errors? 

I wonder if the early error check can be rewritten to:
> It is a Syntax Error if ParseText(Time DateTimeUTCOffset[~Z], DateSpecMonthDay) is a Parse Node.

**Comment by ptomato** [comment]
I guess we could do that because the early errors apply recursively? i.e. ParseText specifically says to analyze the source text for early error conditions, so IsValidMonthDay would already be checked in the _DateSpecMonthDay_ parse.
