### ISSUE TITLE
Temporal.PlainDateTime.prototype.with: result.[[Time]] is never START-OF-DAY

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#3000]
`Temporal.PlainDateTime.prototype.with`, step 18:
> 18. If result.[[Time]] is start-of-day, then

But `result.[[Time]]` is always a Time Record.

**Comment by ptomato** [comment]
Thanks! I also found this while I was working on #2949 and fixed it alongside, but I'll make sure to make it a separate commit when I open the PR.
