### ISSUE TITLE
Temporal.Duration.prototype.toString: If-condition should use "and" instead of "or"

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#3009]
Temporal.Duration.prototype.toString, step 10:
> 10. If precision.[[Unit]] is nanosecond or precision.[[Increment]] = 1, then

`or` should instead be `and`.

**Comment by ptomato** [comment]
Thanks for catching this as well. It's a semantic change that was introduced by mistake in 730e6767150f84a0764bdb8884edf59caf8107c6 (#2943) and so did not have consensus, therefore I'm assuming it does not need consensus to revert it.
