### ISSUE TITLE
DisambiguatePossibleEpochNanoseconds: GetOffsetNanosecondsFor called with ISO Date-Time Record

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#3010]
DisambiguatePossibleEpochNanoseconds, steps 6-9:
> 6. Let before be the latest possible ISO Date-Time Record for which CompareISODateTime(before, isoDateTime) = -1 and ! GetPossibleEpochNanoseconds(timeZone, before) is not empty.
> 7. Let after be the earliest possible ISO Date-Time Record for which CompareISODateTime(after, isoDateTime) = 1 and ! GetPossibleEpochNanoseconds(timeZone, after) is not empty.
> 8. Let offsetBefore be GetOffsetNanosecondsFor(timeZone, before).
> 9. Let offsetAfter be GetOffsetNanosecondsFor(timeZone, after).

But `GetOffsetNanosecondsFor` expects a `BigInt` input.

**Comment by ptomato** [comment]
Thanks for catching! This is a regression from #2925 that fails a type assertion, so I'm going to assume it doesn't need consensus to correct it.
