### ISSUE TITLE
`Temporal.Now` documentation has incorrect `Temporal.Now.timeZone` default parameters

### ISSUE THREAD

**Issue by simonvarey** [tc39/proposal-temporal#3013]
The documentation for `Temporal.Now` describes the default parameters for `Temporal.Now.zonedDateTimeISO`, `Temporal.Now.plainDateTimeISO`, `Temporal.Now.plainDateISO` and `Temporal.Now.plainTimeISO` as equaling `Temporal.Now.timeZone`, which does not exist in the documentation or the polyfill. These parameters should be changed to `Temporal.Now.timeZoneId`.

**Comment by ptomato** [comment]
Thanks for the report. I'll fix this in the next editorial PR.

**Comment by ptomato** [comment]
Fixed in #3027.
