### ISSUE TITLE
DivideTimeDuration and TotalTimeDuration can be merged

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#3020]
`get Temporal.ZonedDateTime.prototype.hoursInDay`, step 10:
> 10. Return 𝔽(DivideTimeDuration(diff, 3.6 × 10**12)).

Can be replaced with:
> 10. Return 𝔽(TotalTimeDuration(diff, HOUR)).

`RoundTimeDuration`, step 1.a.
> 1.a. Let fractionalDays be duration.[[Date]].[[Days]] + DivideTimeDuration(duration.[[Time]], nsPerDay).

Can be replaced with:
> 1.a. Let fractionalDays be duration.[[Date]].[[Days]] + TotalTimeDuration(duration.[[Time]], DAY).

`NudgeToDayOrTime`, steps 5-6:
> 5. Let wholeDays be truncate(DivideTimeDuration(timeDuration, nsPerDay)).
> 6. Let roundedWholeDays be truncate(DivideTimeDuration(roundedNorm, nsPerDay)).

Can be replaced with:
> 5. Let wholeDays be truncate(TotalTimeDuration(timeDuration, DAY)).
> 6. Let roundedWholeDays be truncate(TotalTimeDuration(roundedNorm, DAY)).

**Comment by ptomato** [comment]
Nice catch!
