### ISSUE TITLE
Argument types for options in plus, minus, and difference

### ISSUE THREAD

**Issue by sffc** [tc39/proposal-temporal#359]
The current docs have the _disambiguation_ option as a plain argument in Temporal.*.prototype.plus and .minus, and #333 adds _largestElementInResult_ also as a plain argument.

It might be better to have these be in an options bag, like:

```javascript
date.minus(duration, { disambiguation: "balance" });
date1.difference(date2, { largestElementInResult: "days" });
```

It's more verbose, but I would argue that it's more readable, and it's definitely more future-proof in case we find there are more options we want to add in the future.

**Comment by ptomato** [comment]
This seems like it would be good to do after #260.
