### ISSUE TITLE
Time forward testing

### ISSUE THREAD

**Issue by maggiepint** [tc39/proposal-temporal#36]
Libraries like Moment provide a way to override the "current time" with a function of one's choice for the purpose of time-forward testing.

Do we provide a way to do this or just let people monkey patch the instant object?

**Comment by apaprocki** [comment]
Do people usually do that testing from Node or in the browser? It seems like something that needs to be provided by the engine host environment rather than from within the script itself so that it would also affect `Date` (and anything else, like native modules) and not just the new API.

**Comment by maggiepint** [comment]
I make heavy use of NodaTime's `IClock` interface in my .NET code. It isn't exactly proper 'time forward' testing where the entire environment is rolled forward, but it can still be used to test paths around leap year and DST transitions - which I find quite useful.

**Comment by domenic** [comment]
It seems problematic to introduce such a feature without heavy host integration. E.g. what is its impact on setTimeout, event.timeStamp, etc. I'd suggest leaving it out of this proposal; it has enough weight to be a large proposal in its own, and if done properly will require stakeholders outside TC39.

**Comment by pipobscure** [comment]
Can we close this as unwanted? Especially in light of the debate in #73 ?
