### ISSUE TITLE
Temporal.Duration.from and disambiguation = "balance"

### ISSUE THREAD

**Issue by sffc** [tc39/proposal-temporal#388]
*Split from #324*

From @sffc:

*Use case:* I want to be able to say, "this video is 100 seconds long", and have Temporal automatically fix that to be 1 minute and 40 seconds.

My expectation is that `disambiguation: "balance"` would do this, but it seems it doesn't, based on the polyfill:

```javascript
> Temporal.Duration.from({ seconds: 100, disambiguation: "balance" }).toString()
'PT100S'
```

My expected output would be "PT1M40S" instead.

-----

From @ptomato:

Agreed, this kind of ties in to the discussion about the largest-element cutoff parameter in #307, are Duration objects with too-high values valid? As implemented, currently the polyfill only constrains or balances negative numbers.

-----

From @sffc:

I think it's *valid* to have a Duration object with "too-high" values; but Temporal should also give a way to balance the fields if I specifically request that behavior.

**Comment by ptomato** [comment]
Meeting Feb 20: Balance on Duration.from() should convert things to the largest possible unit, up to hours. (Not days, months, or years.)
