### ISSUE TITLE
Should Absolute#getEpochSeconds/getEpochMilliseconds return Number or BigInt?

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-temporal#420]
Looks like the spec and the polyfill currently disagree. I have no strong opinion on which one to pick.

**Comment by ryzokuken** [comment]
On one hand, `Number` allows us to interoperate with `Date`, but then `BigInt` is more consistent with the behavior for epochnanos.

**Comment by jasonwilliams** [comment]
`getEpochSeconds()` would make sense to keep as number considering the interoperability with other libraries (moment.js etc) and legacy Date. 

`getEpochMilliseconds` and lower however you could have as BigInt

**Comment by ryzokuken** [comment]
@sffc @pipobscure @gibson042 @ljharb @ptomato thoughts?

**Comment by ptomato** [comment]
Since we've decided to give Absolute the same range as legacy Date (epoch ± 1e8 days), it's not possible for these methods to return numbers that are beyond `Number.MAX_SAFE_INTEGER`. So I think Numbers should be used for these. In my opinion BigInt should only be used in places where unsafe integers are possible values.

**Comment by pipobscure** [comment]
The way this was intended was epochSeconds & epochMilliseconds to return numbers (since the range is fine) and epochMicroseconds & epochNanoseconds to return BigInt for the improved range.

**Comment by jasonwilliams** [comment]
> The way this was intended was epochSeconds & epochMilliseconds to return numbers (since the range is fine) and epochMicroseconds & epochNanoseconds to return BigInt for the improved range.

I think we have consensus on this @ryzokuken
