### ISSUE TITLE
startOf and endOf operations?

### ISSUE THREAD

**Issue by rxaviers** [tc39/proposal-temporal#46]
Any plans to include ala-moment startOf and endOf operations?

**Comment by maggiepint** [comment]
They're certainly helpful, but I wonder if given the API surface here they might be more appropriate as an add-on proposal?

**Comment by ryzokuken** [comment]
I’m closing this as it seems there’s nothing more to be discussed here as per @maggiepint’s comment (https://github.com/tc39/proposal-temporal/issues/46#issuecomment-318479857).

@rxaviers please feel free to reopen if you think this should be reconsidered.
