### ISSUE TITLE
Review ToInteger calls

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-temporal#493]
In particular, those can return ±∞, and I'm not quite sure we handle that correctly in all cases. This certainly needs tests, too.

**Comment by littledan** [comment]
Hmm, should we go to 0 in these cases? Or throw an exception?

**Comment by Ms2ger** [comment]
Probably depends on the case; if we're applying a disambiguation option, we could probably throw for "reject" and "balance", and clamp for "constrain", for example.
