### ISSUE TITLE
[402] Decide how to number months in lunisolar calendars

### ISSUE THREAD

**Issue by sffc** [tc39/proposal-temporal#573]
Lunisolar calendars, like Hebrew and Chinese, don't have the same months in every year.

- Hebrew: the month "Adar" is sometimes duplicated into "Adar I" and the leap month "Adar II".  When Adar II is added, the indices for all subsequent months that year increase by 1.
- Chinese: when a leap month is added, it could duplicate any of the twelve months, depending on the moon and solar cycle for that year.

The numbering here is not relevant for the Temporal data model; this question is relevant for the implementation of these calendars in 402.  I am posting it here because it is relevant for the polyfill.

Related: https://github.com/tc39/proposal-intl-displaynames/issues/55.  Ideally, there will be a way to uniquely identify each month and leap month such that we can access the correct display name.

In the above issue, I posted four options:

1. Month is an integer, leap months use the same numeric value as their non-leap equivalent, and we add an additional optional argument which takes "isLeapMonth".  For Chinese, that argument would be true or false.  For Hebrew, we would need three cases, since "Adar", "Adar I", and "Adar II" are all separate names.
    - **Problem:** The user needs to know to use the optional argument.  If they pass their month value from Temporal directly into Intl.DisplayNames, they might miss crucial information.
2. Month is an integer, and we create special numeric values to represent the leap months.  For example, in Chinese, a negative number could be the leap version of the corresponding positive number.  In Hebrew, we could make 12 be "Adar", 13 be "Adar I", and 14 be "Adar II".
    - **Problem:** This might not be backwards-compatible due to the observation in https://github.com/tc39/proposal-intl-displaynames/issues/55#issuecomment-560160386.
3. Month is not an integer but rather is a complex type depending on the calendar system.  For example, the Hebrew calendar could have something like `[12]` for "Adar", `[12, false]` for "Adar I", and `[12, true]` for "Adar II".  The Chinese calendar could have `[4]` for "Sìyuè" and `[4, true]` for "Rùn Sìyuè".
    - **Problem:** We lose a certain simplicity such as the ability to compare two month values using the `<` or `>` operator.
4. Month is a first-class type, Temporal.Month, with semantics defined by the calendar system.
    - **Problem:** This would need to be proposed to Temporal.  So far all Temporal types have been clean integers, and this would add complexity to the data model.

I will add some more options:

5. Count the months from 1 in each year.  A particular number may correspond to a different month depending on the year.  In Intl.DisplayNames, require that both the month index and the reference year be provided.
6. Same as 5, except make Temporal.YearMonth the type to pass to Intl.DisplayNames to get the month name.

@FrankYFTang

**Comment by ptomato** [comment]
#1203 seems to be where the up-to-date discussion is happening for this, I'll close this one in favour of that one.
