### ISSUE TITLE
Suggestion: throw for common invalid arguments cases

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#615]
At least once per hour of using Temporal, I accidentally exclude an `s` when calling a method that expects a Duration-like object, or accidentally include an `s` when calling a method that expects one of the other Temporal types.  Less commonly, I'll accidentally pass an `XxxLike` object to a Temporal object constructor. 

```js
// Expected: throws
// Actual: all-zero results
Temporal.Time.from({hours: 12});
Temporal.Duration.from({hour: 12});
new Temporal.Duration({year: 2020, month: 1, day: 1});
new Temporal.Time({hour: 10, minute: 30});
```

Today, these cases all fail silently, treating my input object as `{}`, which is effectively an all-zero object. These bugs can be hard to track down because zero is also valid in many use cases.

Suggestion: can Temporal throw in cases when a singular field name is expected but the plural variant is supplied, or vice versa? Or when an XxxxLike object is passed to a Temporal object constructor?

**Comment by ptomato** [comment]
I believe this is discussed in #325, I'll move it over there.
