### ISSUE TITLE
Will Date, DateTime, etc. have a `calendar` property?

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#635]
https://github.com/tc39/proposal-temporal/blob/7424e246dfca89dcd8f2734b902c1c647c9042b1/docs/calendar-draft.md#iso-strings-with-calendar-hint implies that Date, DateTime, etc. will get a `calendar` property. If such a property will exist (IMHO it should), then it should probably be called out explicitly in the [Changes to other Temporal APIs](https://github.com/tc39/proposal-temporal/blob/7424e246dfca89dcd8f2734b902c1c647c9042b1/docs/calendar-draft.md#changes-to-other-temporal-apis) section.

**Comment by ptomato** [comment]
They will indeed have a `calendar` property but since I'm very close to finishing the branch where it is implemented, I don't think it's necessary to update the calendar-draft.md right now.
