### ISSUE TITLE
Custom Time Zones and 'TimeZone.prototype.toJSON'

### ISSUE THREAD

**Issue by rbuckton** [tc39/proposal-temporal#669]
In the API docs, a `TimeZone` subclass needs to override `getOffsetNanosecondsFor`, `getPossibleAbsolutesFor`, and `toString`. Currently, `TimeZone.prototype.toJSON` is merely a reference to the built-in `TimeZone.prototype.toString` method. Should `toJSON` instead *call* `this.toString()`, or is it expected that authors of custom time zones should override `toJSON` themselves to change the representation?

**Comment by ptomato** [comment]
I'd say the former.

**Comment by ptomato** [comment]
Fixed by #681.
