### ISSUE TITLE
Add With functions for all date parts

### ISSUE THREAD

**Issue by maggiepint** [tc39/proposal-temporal#70]
It's only on date right now in the spec text.

**Comment by gibson042** [comment]
The polyfill defines all of the following, which I believe is correct (but spec text has yet to catch up):
* Instant.prototype.withZone
* DateTime.prototype.with
* DateTime.prototype.withZone
* Date.prototype.withTime
* Date.prototype.with
* Time.prototype.withDate
* Time.prototype.with
* YearMonth.prototype.withDay
* YearMonth.prototype.with
* MonthDay.prototype.withYear
* MonthDay.prototype.with
* ZonedDateTime.prototype.with
* ZonedDateTime.prototype.sameDateTimeWithZone, which could be removed (it's really just really a shorthand for `getDateTime().withZone`) but if kept should probably be withZoneSameDateTime for good alphabetic clustering
* ZonedDateTime.prototype.sameInstantWithZone, which could be removed (it's really just a shorthand for `getInstant().withZone`) but if kept should probably be withZoneSameInstant for good alphabetic clustering

**Comment by ryzokuken** [comment]
IIUC, this has been appropriately addressed with the current state of the API, so I'm closing this. Please feel free to reopen if necessary.
