### ISSUE TITLE
Write spec text for accepted ISO formats on a per object basis

### ISSUE THREAD

**Issue by maggiepint** [tc39/proposal-temporal#71]

**Comment by pipobscure** [comment]
Didn't we say we'd explicitly describe the `toString()` methods and only accept that exact format in `.fromString()` and then leave parsing out of scope? Or is this already a result of the next meeting?

**Comment by pipobscure** [comment]
Is this https://github.com/tc39/proposal-temporal/pull/65/files#diff-935dfcf8322fcb97745317a026a9c7b8R72 what you were referring to?

**Comment by maggiepint** [comment]
Ya. Just have to make sure it's in Sasha's work and reflected in the readme.

**Comment by ryzokuken** [comment]
@maggiepint are you still working on this?
