### ISSUE TITLE
Document that `with` methods accept Temporal object instances

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#713]
Because in #403 it was decided that fields shouldn't be enumerable, I assumed that code like the following was required to use `with` with Temporal object instances.

```js
const dt = Temporal.now.dateTime();
const midnight = Temporal.Time.from('00:00');
const newYear = Temporal.MonthDay.from({month: 1, day: 1});

const todayMidnight = dt.with({...midnight.getFields()});
const thisJan1 = dt.with({...newYear.getFields()});
```

This assumption was wrong, which seems obvious now. But it still took me a few weeks to realize that I can use this much easier and intuitive code:

```js
// much easier!
const todayMidnight = dt.with(midnight);
const thisJan1 = dt.with(newYear);

// the same trick works with `from` too!  (this is already documented though)
Temporal.DateTime.from(Temporal.now.date())
Temporal.Time.from(Temporal.now.dateTime())
```

In a quick look at the docs for `with`, I only saw example code with object literals, which made this trick harder to discover.  I think I'd slotted these methods into a mental box that said "only accepts object literals".  This is obviously wrong in retrospect but is a good example of how unintended messages in the docs can persist in novice developers' heads.

IMHO, it's worth adding additional samples to documentation for `with` to illustrate that even though you can't spread a Temporal instance into an object, you *can* pass it into `with` of another compatible Temporal instance.

**Comment by ptomato** [comment]
I think the cases that are worth documenting are:
- Date.with(YearMonth)
- Date.with(MonthDay)
- DateTime.with(Time)
- DateTime.with(Date)
- DateTime.with(YearMonth)
- DateTime.with(MonthDay)
Anything else, we should probably not be encouraging, as it would overwrite all the fields and should probably better use from() or one of the type conversion methods.
