### ISSUE TITLE
Allow negative durations?

### ISSUE THREAD

**Issue by thojanssens** [tc39/proposal-temporal#731]
I'm having the following error when specifying a negative duration:

> ecmascript.mjs:363 Uncaught (in promise) RangeError: negative values not allowed as duration fields

Does that mean that I have to bloat my code with `if`'s to call the appropriate function `plus`/`minus` according to the sign of the given duration?

**Comment by ptomato** [comment]
Yes, negative durations seems to be the area that we are getting the strongest feedback about. The current discussion is on #558, so I'd like to consolidate this into that one.
