### ISSUE TITLE
toLocaleString issue

### ISSUE THREAD

**Issue by thojanssens** [tc39/proposal-temporal#733]
I run the following code to get the formatted localized day of week from a date time:
```
Temporal.now.dateTime().toLocaleString('en-US', { weekday: 'long' })
```
But I get more than the day of week:

> "Tuesday, 7/7/2020, 11:33:30 AM"

I expect `toLocaleString` to work like it would for `Date`:

```
new Date().toLocaleString('en-US', { weekday: 'long' })
```
> "Tuesday"

**Comment by ptomato** [comment]
You found a bug, thanks!
