### ISSUE TITLE
Cookbook docs: Current Date incorrectly reference stackoverflow question (date vs datetime)

### ISSUE THREAD

**Issue by sadams** [tc39/proposal-temporal#752]
https://github.com/tc39/proposal-temporal/blob/main/docs/cookbook/getCurrentDate.mjs#L4 references a stackoverflow question which is about getting just the current date (not time). The example given returns a datetime object. 

```
const { Temporal, Intl } = require('proposal-temporal');

const dateTime = Temporal.now.dateTime(); // Gets the current date
console.log(dateTime.toString());
console.log(new Date().toString());
console.log(new Date().toISOString());

> 2020-07-10T20:57:34.529054502
> Fri Jul 10 2020 20:57:34 GMT+0100 (British Summer Time)
> 2020-07-10T19:57:34.541Z
```

If the reference is incorrect (as the example implies), explaining the difference between what you can get from the existing `Date` vs `Temporal` (e.g. timezone/ISO standard) would be valuable.

**Comment by ptomato** [comment]
Thanks for pointing it out, will clarify in the example!
