### ISSUE TITLE
Test polyfill on environment without Intl

### ISSUE THREAD

**Issue by ptomato** [tc39/proposal-temporal#764]
The toLocaleString() methods should do whatever Date.toLocaleString() does if Intl is not present, I guess?

**Comment by ptomato** [comment]
Closing. It seems unreasonable for the polyfill to work without Intl when it's developed on an Intl environment. However, the spec text should take the possibility of no Intl into account (and it does.)

**Comment by ljharb** [comment]
@ptomato i don't think it's unreasonable at all; code that requires Intl is not universal, and such code would still want Temporal to work.

**Comment by ptomato** [comment]
There seems to be some confusion here — this is not about whether Temporal works in environments without Intl. This is about whether effort should be spent to ensure that the polyfill in this repo (which, as we have agreed, at this point is not intended to be production quality) can handle environments without Intl, and has automated tests ensuring that. If someone wants to ensure that support then they can, but in our meeting this morning we didn't think it was reasonable to spend effort on that.

**Comment by ljharb** [comment]
@ptomato gotcha, that makes sense :-) i agree this doesn't matter for the soon-to-be-deprecated polyfill, but i hope if anyone makes a new polyfill once temporal hits stage 3, they'd account for this use case.
