### ISSUE TITLE
Absolute doesnt have 'with' method?

### ISSUE THREAD

**Issue by henryw374** [tc39/proposal-temporal#800]
The cookbook suggests all temporal types do have this: https://tc39.es/proposal-temporal/docs/cookbook.html#round-a-time-down-to-whole-hours "Use the with() method of each Temporal type if you want to round or balance the fields."

**Comment by ptomato** [comment]
Good catch, thanks. Temporal.Absolute doesn't have it because it doesn't have any fields, only a timestamp in nanoseconds. If you want to round an Absolute then you have to convert it to a calendar-based type such as Temporal.DateTime. I will clarify this in the documentation.
