### ISSUE TITLE
Consider Making Now a Static Constructor Method

### ISSUE THREAD

**Issue by daniel-nagy** [tc39/proposal-temporal#842]
I'm struggling to appreciate `Temporal.now`. I think these make more sense as static constructors on the individual data types just like `from`, e.g.

```js
Temporal.Absolute.now()
Temporal.DateTime.now()
Temporal.Date.now()
Temporal.Time.now()
Temporal.TimeZone.current() // or Temporal.TimeZone.system()
```

**Comment by ptomato** [comment]
Thanks for consolidating it :smile:
