### ISSUE TITLE
Rendered proposal spec text

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-temporal#85]
I don't see a link to the rendered proposal on this repository. Is it hosted somewhere?

**Comment by maggiepint** [comment]
On my agenda to do today!

**Comment by littledan** [comment]
Did you run into any issues?

**Comment by mj1856** [comment]
There were lots of little formatting issues, but I have resolved them enough to render what has already been written.  The file is `spec-rendered.html` in the root of the project.  Viewable [here](http://htmlpreview.github.io/?https://github.com/tc39/proposal-temporal/blob/master/spec-rendered.html).
