### ISSUE TITLE
Consistent capitalization for "ISO"

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-temporal#897]
We've got `getISOFields()` and `refISODay`, but `isoYear`.

**Comment by ptomato** [comment]
That was based on comments on #622. Reading https://stackoverflow.com/questions/15526107/acronyms-in-camelcase it seems like this is a matter of hotly debated taste. Are there precedents anywhere else in ECMA-262 or 402?

**Comment by ljharb** [comment]
Initialisms should be all lowercase or all uppercase. I don't think it's particularly inconsistent to have this combination, and `ISOYear` would look weird (and imply it's a constructor).

**Comment by Ms2ger** [comment]
No objection from me if this was intentional.

**Comment by ptomato** [comment]
OK to close this? Please reopen if we should continue discussing.
