### ISSUE TITLE
Only call NormalizeOptionsObject once per value

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-temporal#899]
I guess this might actually not be observable, but it's more consistent with the way `GetOption` is used in ECMA402.

**Comment by ptomato** [comment]
I don't think it is observable, but you're right, it would be cleaner. Do you think we should remove these abstract ops and just write GetOption instead?

**Comment by Ms2ger** [comment]
I think it's fine to keep the abstract ops to avoid repeating the strings.
