### ISSUE TITLE
Should the fields object passed to calendar.*FromFields methods have a 'calendar' property?

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-temporal#905]

**Comment by sffc** [comment]
Do we pass the user-supplied fields object to calendar.\*FromFields, or do we make a new object?  If we pass the user-supplied one directly, we shouldn't bother with removing the calendar.  If we re-create a new object, then I think it makes sense to remove the calendar field.

**Comment by Ms2ger** [comment]
From a quick `grep`, it seems like only the `from` methods pass through a user-supplied object (and I'd probably prefer to change those as well for consistency).
