### ISSUE TITLE
.equals

### ISSUE THREAD

**Issue by bakkot** [tc39/proposal-temporal#96]
I think it would be useful to ask if two Temporal objects (at least of the same time) represent the same time.

**Comment by pipobscure** [comment]
For `Instant` and `ZonedDateTime` this is possible by comparing:

`instant.nanoseconds === zoned.instant.nanoseconds`

For CivilObjects, equality/sorting is harder. There you'd have to approcimate by going with:

`civildatetime1.toString() === civildatetime2.toString()`

**Comment by ljharb** [comment]
Would it make sense to have an instance method that could abstract away the “harder” parts?

**Comment by pipobscure** [comment]
@ljharb I can imagine having a `.compare()` method on `Civil*` objects that return an `Array.prototype.sort()` compatible `Number`. For `Instant` and `ZonedDateType` I'd think it's easy enough to just reference the `instant.nanoseconds` or `zoned.instant.nanoseconds` member

**Comment by ryzokuken** [comment]
Closing this in favor of https://github.com/tc39/proposal-temporal/issues/109, which could be used for discussing everything related to comparison and difference functionality.
