### ISSUE TITLE
DurationOptions reject support

### ISSUE THREAD

**Issue by Pavel-Husakouski** [tc39/proposal-temporal#960]
DurationOptions is declared like this
```
export type DurationOptions = {
    overflow: 'constrain' | 'balance' | 'reject';
};
```
However `Duration.from({seconds: 1}, {overflow: 'reject'})` throws an exception `RangeError: overflow must be one of constrain, balance, not reject`
Looks like there is either a discrepancy between supported overflow kinds or wrong TS typing.

**Comment by ryzokuken** [comment]
You're right, the TS types are incorrect.

```javascript
  ToTemporalDurationOverflow: (options) => {
    options = ES.NormalizeOptionsObject(options);
    return ES.GetOption(options, 'overflow', ['constrain', 'balance'], 'constrain');
  },
```

I will make a PR to update the TS types.
